<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>Annotated Index</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.3-rc2 -->
<center>
<a class="qindex" href="index.php">Main Page</a> &nbsp; <a class="qindex" href="modules.php">Modules</a> &nbsp; <a class="qindex" href="hierarchy.php">Class Hierarchy</a> &nbsp; <a class="qindex" href="classes.php">Alphabetical List</a> &nbsp; <a class="qindex" href="annotated.php">Compound List</a> &nbsp; <a class="qindex" href="files.php">File List</a> &nbsp; <a class="qindex" href="functions.php">Compound Members</a> &nbsp; </center>
<hr><h1>AE Engine Compound List</h1>Here are the classes, structs, unions and interfaces with brief descriptions:<table>
  <tr><td class="indexkey"><a class="el" href="structaeActiveEvent.php">aeActiveEvent</a></td><td class="indexvalue">Holds info for app focus gain/lost event</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaeBase.php">aeBase</a></td><td class="indexvalue">This is a base class for all objects</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaeBlockDescriptor.php">aeBlockDescriptor</a></td><td class="indexvalue">This class describes allocated memory-chunks</td></tr>
  <tr><td class="indexkey"><a class="el" href="structbmpFileHeader.php">bmpFileHeader</a></td><td class="indexvalue">BITMAPFILEHEADER struct</td></tr>
  <tr><td class="indexkey"><a class="el" href="structbmpHeader.php">bmpHeader</a></td><td class="indexvalue">BITMAPINFOHEADER struct</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaeCamera.php">aeCamera</a></td><td class="indexvalue">This is a single camera object that can be attached to the engine</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaeColor3.php">aeColor3</a></td><td class="indexvalue">A class representing RGB color</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaeColor4.php">aeColor4</a></td><td class="indexvalue">A class representing RGBA color</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaeDataBuffer.php">aeDataBuffer</a></td><td class="indexvalue">A generic data buffer class</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaeEngine.php">aeEngine</a></td><td class="indexvalue">Interface to the engine</td></tr>
  <tr><td class="indexkey"><a class="el" href="structaeEngineflags.php">aeEngineflags</a></td><td class="indexvalue">Engine flags structure</td></tr>
  <tr><td class="indexkey"><a class="el" href="structaeEvent.php">aeEvent</a></td><td class="indexvalue">The AE event structure</td></tr>
  <tr><td class="indexkey"><a class="el" href="structaeEventCommand.php">aeEventCommand</a></td><td class="indexvalue">Event command struct</td></tr>
  <tr><td class="indexkey"><a class="el" href="structframe__t.php">frame_t</a></td><td class="indexvalue">A single frame structure</td></tr>
  <tr><td class="indexkey"><a class="el" href="structframePoint__t.php">framePoint_t</a></td><td class="indexvalue">A single frame point structure</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaeFrustumCuller.php">aeFrustumCuller</a></td><td class="indexvalue">Engine level Interface to the frustum culler</td></tr>
  <tr><td class="indexkey"><a class="el" href="structaeKeyboardEvent.php">aeKeyboardEvent</a></td><td class="indexvalue">Keyboard event struct</td></tr>
  <tr><td class="indexkey"><a class="el" href="structaeKeySym.php">aeKeySym</a></td><td class="indexvalue">Key press info</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaeLine.php">aeLine</a></td><td class="indexvalue">A 3D line</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaeMaterial.php">aeMaterial</a></td><td class="indexvalue">This class represents a material that can be applied onto an object</td></tr>
  <tr><td class="indexkey"><a class="el" href="structmd2Header__t.php">md2Header_t</a></td><td class="indexvalue">A MD2 header structure</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaeMD2Object.php">aeMD2Object</a></td><td class="indexvalue">This class represents a single MD2 model</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaeMemoryManager.php">aeMemoryManager</a></td><td class="indexvalue">The AE memory manager</td></tr>
  <tr><td class="indexkey"><a class="el" href="structmesh__t.php">mesh_t</a></td><td class="indexvalue">A mesh structure</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaeModel.php">aeModel</a></td><td class="indexvalue">A 3D model object</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaeModelLoader.php">aeModelLoader</a></td><td class="indexvalue">Interface to the model loader plugin</td></tr>
  <tr><td class="indexkey"><a class="el" href="structaeMouseButtonEvent.php">aeMouseButtonEvent</a></td><td class="indexvalue">Mouse button event struct</td></tr>
  <tr><td class="indexkey"><a class="el" href="structaeMouseMotionEvent.php">aeMouseMotionEvent</a></td><td class="indexvalue">Mouse motion event struct</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaeObject.php">aeObject</a></td><td class="indexvalue">A base class for all objects</td></tr>
  <tr><td class="indexkey"><a class="el" href="structpcxHeader.php">pcxHeader</a></td><td class="indexvalue">(A partial) PCX file header</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaePlugin.php">aePlugin</a></td><td class="indexvalue">A base class for all plugins</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaePolygon.php">aePolygon</a></td><td class="indexvalue">A 3D polygon</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaeQuad.php">aeQuad</a></td><td class="indexvalue">A 3D quad</td></tr>
  <tr><td class="indexkey"><a class="el" href="structaeQuitEvent.php">aeQuitEvent</a></td><td class="indexvalue">Quit event</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaeRegistry.php">aeRegistry</a></td><td class="indexvalue">This class is an interface to the global object registry</td></tr>
  <tr><td class="indexkey"><a class="el" href="structstIndex__t.php">stIndex_t</a></td><td class="indexvalue">A texture coordinate index structure</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaeSystem.php">aeSystem</a></td><td class="indexvalue">This class is an interface to the operating system and the window manager</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaeTerrMan.php">aeTerrMan</a></td><td class="indexvalue">Interface to the terrain plugin</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaeTexCoord2.php">aeTexCoord2</a></td><td class="indexvalue">A class representing single 2D texture coordinate</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaeTexture.php">aeTexture</a></td><td class="indexvalue">A single texture object</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaeTextureLoader.php">aeTextureLoader</a></td><td class="indexvalue">Interface to the texture loader</td></tr>
  <tr><td class="indexkey"><a class="el" href="structtgaHeader.php">tgaHeader</a></td><td class="indexvalue">TGA file header</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaeTimer.php">aeTimer</a></td><td class="indexvalue">This is a general virtual/system timer class</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaeTriangle.php">aeTriangle</a></td><td class="indexvalue">A 3D triangle</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaeUtil.php">aeUtil</a></td><td class="indexvalue">General static utility functions</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaeVector.php">aeVector</a></td><td class="indexvalue">A 2D vector</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaeVector3.php">aeVector3</a></td><td class="indexvalue">A 3D vector</td></tr>
  <tr><td class="indexkey"><a class="el" href="classaeVector4.php">aeVector4</a></td><td class="indexvalue">A 4D vector</td></tr>
</table>
<hr><address style="align: right;"><small>Generated on Sun Mar 2 01:14:23 2003 for AE Engine by
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border=0 
width=110 height=53></a>1.3-rc2 </small></address>
</body>
</html>
