<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>aeBase class Reference</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.3-rc2 -->
<center>
<a class="qindex" href="index.php">Main Page</a> &nbsp; <a class="qindex" href="modules.php">Modules</a> &nbsp; <a class="qindex" href="hierarchy.php">Class Hierarchy</a> &nbsp; <a class="qindex" href="classes.php">Alphabetical List</a> &nbsp; <a class="qindex" href="annotated.php">Compound List</a> &nbsp; <a class="qindex" href="files.php">File List</a> &nbsp; <a class="qindex" href="functions.php">Compound Members</a> &nbsp; </center>
<hr><h1>aeBase Class Reference</h1>This is a base class for all objects. 
<a href="#_details">More...</a>
<p>
<code>#include &lt;<a class="el" href="base_8h-source.php">base.h</a>&gt;</code>
<p>
<p>Inheritance diagram for aeBase:
<p><center><img src="classaeBase.png" usemap="#aeBase_map" border="0" alt=""></center>
<map name="aeBase_map">
<area href="classaeCamera.php" alt="aeCamera" shape="rect" coords="133,56,256,80">
<area href="classaeDataBuffer.php" alt="aeDataBuffer" shape="rect" coords="133,112,256,136">
<area href="classaeEngine.php" alt="aeEngine" shape="rect" coords="133,168,256,192">
<area href="classaeFrustumCuller.php" alt="aeFrustumCuller" shape="rect" coords="133,224,256,248">
<area href="classaeMaterial.php" alt="aeMaterial" shape="rect" coords="133,280,256,304">
<area href="classaeMemoryManager.php" alt="aeMemoryManager" shape="rect" coords="133,336,256,360">
<area href="classaeObject.php" alt="aeObject" shape="rect" coords="133,392,256,416">
<area href="classaePlugin.php" alt="aePlugin" shape="rect" coords="133,448,256,472">
<area href="classaeRegistry.php" alt="aeRegistry" shape="rect" coords="133,504,256,528">
<area href="classaeSystem.php" alt="aeSystem" shape="rect" coords="133,560,256,584">
<area href="classaeTexture.php" alt="aeTexture" shape="rect" coords="133,616,256,640">
<area href="classaeTimer.php" alt="aeTimer" shape="rect" coords="133,672,256,696">
</map>
<a href="classaeBase-members.php">List of all members.</a><table border=0 cellpadding=0 cellspacing=0>
<tr><td></td></tr>
<tr><td colspan=2><br><h2>Protected Methods</h2></td></tr>
<tr><td nowrap align=right valign=top>virtual void&nbsp;</td><td valign=bottom><a class="el" href="classaeBase.php#b0">Report</a> (int loglevel, const char *msg,...)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>General in-engine report function with loglevel.</em> <a href="#b0"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>virtual void&nbsp;</td><td valign=bottom><a class="el" href="classaeBase.php#b1">ASSERT</a> (bool isok, char *desc,...)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>General in-engine assert function.</em> <a href="#b1"></a><em></em></font><br><br></td></tr>
<tr><td colspan=2><br><h2>Protected Attributes</h2></td></tr>
<tr><td nowrap align=right valign=top><a name="n0" doxytag="aeBase::LOGLEVEL"></a>
int&nbsp;</td><td valign=bottom><b>LOGLEVEL</b></td></tr>
</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
This is a base class for all objects.
<p>

<p>
Definition at line <a class="el" href="base_8h-source.php#l00028">28</a> of file <a class="el" href="base_8h-source.php">base.h</a>.<hr><h2>Member Function Documentation</h2>
<a name="b1" doxytag="aeBase::ASSERT"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> virtual void aeBase::ASSERT </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">bool&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>isok</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>char *&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>desc</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>...&nbsp;</td>
          <td class="mdname" nowrap>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [protected, virtual]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
General in-engine assert function.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>isok</em>&nbsp;</td><td>Expression to test. </td></tr>
    <tr><td valign=top><em>desc</em>&nbsp;</td><td>Description to print out if the expression fails (can include printf style formatting). </td></tr>
    <tr><td valign=top><em>...</em>&nbsp;</td><td>Format variables (think of printf).</td></tr>
  </table>
</dl>
    </td>
  </tr>
</table>
<a name="b0" doxytag="aeBase::Report"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> virtual void aeBase::Report </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">int&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>loglevel</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>const char *&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>msg</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>...&nbsp;</td>
          <td class="mdname" nowrap>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [protected, virtual]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
General in-engine report function with loglevel.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>loglevel</em>&nbsp;</td><td>Loglevel. </td></tr>
    <tr><td valign=top><em>msg</em>&nbsp;</td><td>Message (with possible format characters, think of printf). </td></tr>
    <tr><td valign=top><em>...</em>&nbsp;</td><td>Possible format variables (think of printf).</td></tr>
  </table>
</dl>
    </td>
  </tr>
</table>
<hr>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="base_8h-source.php">base.h</a></ul>
<hr><address style="align: right;"><small>Generated on Sun Mar 2 01:14:23 2003 for AE Engine by
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border=0 
width=110 height=53></a>1.3-rc2 </small></address>
</body>
</html>
