<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>aeFrustumCuller class Reference</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.3-rc2 -->
<center>
<a class="qindex" href="index.php">Main Page</a> &nbsp; <a class="qindex" href="modules.php">Modules</a> &nbsp; <a class="qindex" href="hierarchy.php">Class Hierarchy</a> &nbsp; <a class="qindex" href="classes.php">Alphabetical List</a> &nbsp; <a class="qindex" href="annotated.php">Compound List</a> &nbsp; <a class="qindex" href="files.php">File List</a> &nbsp; <a class="qindex" href="functions.php">Compound Members</a> &nbsp; </center>
<hr><h1>aeFrustumCuller Class Reference</h1>Engine level Interface to the frustum culler. 
<a href="#_details">More...</a>
<p>
<code>#include &lt;<a class="el" href="frustumculler_8h-source.php">frustumculler.h</a>&gt;</code>
<p>
<p>Inheritance diagram for aeFrustumCuller:
<p><center><img src="classaeFrustumCuller.png" usemap="#aeFrustumCuller_map" border="0" alt=""></center>
<map name="aeFrustumCuller_map">
<area href="classaeBase.php" alt="aeBase" shape="rect" coords="0,0,105,24">
</map>
<a href="classaeFrustumCuller-members.php">List of all members.</a><table border=0 cellpadding=0 cellspacing=0>
<tr><td></td></tr>
<tr><td colspan=2><br><h2>Public Methods</h2></td></tr>
<tr><td nowrap align=right valign=top>void&nbsp;</td><td valign=bottom><a class="el" href="classaeFrustumCuller.php#a2">ExtractFrustum</a> ()</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Extract the current view-frustum.</em> <a href="#a2"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>bool&nbsp;</td><td valign=bottom><a class="el" href="classaeFrustumCuller.php#a3">PointInFrustum</a> (<a class="el" href="classaeVector3.php">aeVector3</a> point)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Check if a point is in the frustum.</em> <a href="#a3"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>bool&nbsp;</td><td valign=bottom><a class="el" href="classaeFrustumCuller.php#a4">SphereInFrustum</a> (<a class="el" href="classaeVector3.php">aeVector3</a> center, float radius)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Check if an object's bounding sphere is in the frustum.</em> <a href="#a4"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>bool&nbsp;</td><td valign=bottom><a class="el" href="classaeFrustumCuller.php#a5">CubeInFrustum</a> (<a class="el" href="classaeVector3.php">aeVector3</a> center, float size)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Check if an object's bounding box is in the frustum.</em> <a href="#a5"></a><em></em></font><br><br></td></tr>
</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
Engine level Interface to the frustum culler.
<p>

<p>
Definition at line <a class="el" href="frustumculler_8h-source.php#l00035">35</a> of file <a class="el" href="frustumculler_8h-source.php">frustumculler.h</a>.<hr><h2>Member Function Documentation</h2>
<a name="a5" doxytag="aeFrustumCuller::CubeInFrustum"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> bool aeFrustumCuller::CubeInFrustum </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top"><a class="el" href="classaeVector3.php">aeVector3</a>&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>center</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>float&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>size</em></td>
        </tr>
        <tr>
          <td></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Check if an object's bounding box is in the frustum.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>center</em>&nbsp;</td><td>The origin of the object to check. </td></tr>
    <tr><td valign=top><em>size</em>&nbsp;</td><td>The bounding box size (half of the cube's length).</td></tr>
  </table>
</dl>
<dl compact><dt><b>Returns:</b></dt><dd>True if the object's bounding box is visible by the camera, false if not.</dd></dl>
    </td>
  </tr>
</table>
<a name="a2" doxytag="aeFrustumCuller::ExtractFrustum"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> void aeFrustumCuller::ExtractFrustum </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Extract the current view-frustum.
<p>
This is called each frame by the engine rendering loop.    </td>
  </tr>
</table>
<a name="a3" doxytag="aeFrustumCuller::PointInFrustum"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> bool aeFrustumCuller::PointInFrustum </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top"><a class="el" href="classaeVector3.php">aeVector3</a>&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp; <em>point</em>          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Check if a point is in the frustum.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>point</em>&nbsp;</td><td>The point (vertex) to check.</td></tr>
  </table>
</dl>
<dl compact><dt><b>Returns:</b></dt><dd>True if the point is currently visible by the camera, false if not.</dd></dl>
    </td>
  </tr>
</table>
<a name="a4" doxytag="aeFrustumCuller::SphereInFrustum"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> bool aeFrustumCuller::SphereInFrustum </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top"><a class="el" href="classaeVector3.php">aeVector3</a>&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>center</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>float&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>radius</em></td>
        </tr>
        <tr>
          <td></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Check if an object's bounding sphere is in the frustum.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>center</em>&nbsp;</td><td>The origin of the object to check. </td></tr>
    <tr><td valign=top><em>radius</em>&nbsp;</td><td>The bounding sphere radius of the object.</td></tr>
  </table>
</dl>
<dl compact><dt><b>Returns:</b></dt><dd>True if the object's bounding sphere is visible by the camera, false if not.</dd></dl>
    </td>
  </tr>
</table>
<hr>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="frustumculler_8h-source.php">frustumculler.h</a></ul>
<hr><address style="align: right;"><small>Generated on Sun Mar 2 01:14:23 2003 for AE Engine by
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border=0 
width=110 height=53></a>1.3-rc2 </small></address>
</body>
</html>
