<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>aeMD2Object class Reference</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.3-rc2 -->
<center>
<a class="qindex" href="index.php">Main Page</a> &nbsp; <a class="qindex" href="modules.php">Modules</a> &nbsp; <a class="qindex" href="hierarchy.php">Class Hierarchy</a> &nbsp; <a class="qindex" href="classes.php">Alphabetical List</a> &nbsp; <a class="qindex" href="annotated.php">Compound List</a> &nbsp; <a class="qindex" href="files.php">File List</a> &nbsp; <a class="qindex" href="functions.php">Compound Members</a> &nbsp; </center>
<hr><h1>aeMD2Object Class Reference</h1>This class represents a single MD2 model. 
<a href="#_details">More...</a>
<p>
<code>#include &lt;<a class="el" href="md2object_8h-source.php">md2object.h</a>&gt;</code>
<p>
<p>Inheritance diagram for aeMD2Object:
<p><center><img src="classaeMD2Object.png" usemap="#aeMD2Object_map" border="0" alt=""></center>
<map name="aeMD2Object_map">
<area href="classaeModel.php" alt="aeModel" shape="rect" coords="0,112,90,136">
<area href="classaeObject.php" alt="aeObject" shape="rect" coords="0,56,90,80">
<area href="classaeBase.php" alt="aeBase" shape="rect" coords="0,0,90,24">
</map>
<a href="classaeMD2Object-members.php">List of all members.</a><table border=0 cellpadding=0 cellspacing=0>
<tr><td></td></tr>
<tr><td colspan=2><br><h2>Public Methods</h2></td></tr>
<tr><td nowrap align=right valign=top><a name="a0" doxytag="aeMD2Object::aeMD2Object"></a>
&nbsp;</td><td valign=bottom><b>aeMD2Object</b> (char *mdlstr, <a class="el" href="group__aetypedefs.php#a7">aeVector3_vector</a> *vertList, <a class="el" href="group__aetypedefs.php#a8">aeTexCoord2_vector</a> *stList, <a class="el" href="structmesh__t.php">mesh_t</a> *triIdx, unsigned int numframes, unsigned int numverts, unsigned int numtris, unsigned int numst, unsigned int framesize)</td></tr>
<tr><td nowrap align=right valign=top>void&nbsp;</td><td valign=bottom><a class="el" href="classaeMD2Object.php#a2">Draw</a> (<a class="el" href="structaeEngineflags.php">aeEngineflags</a> *)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Draw the model.</em> <a href="#a2"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>int&nbsp;</td><td valign=bottom><a class="el" href="classaeMD2Object.php#a3">Animate</a> (<a class="el" href="structaeEngineflags.php">aeEngineflags</a> *)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Animate the model given a start frame, end frame, and interpolation percentage.</em> <a href="#a3"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>int&nbsp;</td><td valign=bottom><a class="el" href="classaeMD2Object.php#a4">RenderFrame</a> (<a class="el" href="structaeEngineflags.php">aeEngineflags</a> *)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Render a single frame of the model.</em> <a href="#a4"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>void&nbsp;</td><td valign=bottom><a class="el" href="classaeMD2Object.php#a5">SetAnimation</a> (int startframe, int endframe, float percent)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Set model animation given start frame, end frame, and interpolation percentage.</em> <a href="#a5"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>void&nbsp;</td><td valign=bottom><a class="el" href="classaeMD2Object.php#a6">SetFrame</a> (int keyframe)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Set model frame to render.</em> <a href="#a6"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top><a class="el" href="group__mdlldrstructs.php#a0">modelState_t</a>&nbsp;</td><td valign=bottom><a class="el" href="classaeMD2Object.php#a7">GetState</a> ()</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Retrieve animation state for the model.</em> <a href="#a7"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>void&nbsp;</td><td valign=bottom><a class="el" href="classaeMD2Object.php#a8">SetState</a> (<a class="el" href="group__mdlldrstructs.php#a0">modelState_t</a> state)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Set the animation state for the model.</em> <a href="#a8"></a><em></em></font><br><br></td></tr>
</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
This class represents a single MD2 model.
<p>
Normally you don't deal with this class directly, but with the <a class="el" href="classaeModel.php">aeModel</a> class.
<p>
<dl compact><dt><b>See also:</b></dt><dd><a class="el" href="classaeModel.php">aeModel</a> </dd></dl>

<p>

<p>
Definition at line <a class="el" href="md2object_8h-source.php#l00041">41</a> of file <a class="el" href="md2object_8h-source.php">md2object.h</a>.<hr><h2>Member Function Documentation</h2>
<a name="a3" doxytag="aeMD2Object::Animate"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> int aeMD2Object::Animate </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top"><a class="el" href="structaeEngineflags.php">aeEngineflags</a> *&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap><code> [virtual]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Animate the model given a start frame, end frame, and interpolation percentage.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>startFrame</em>&nbsp;</td><td>Starting frame. </td></tr>
    <tr><td valign=top><em>endFrame</em>&nbsp;</td><td>Ending frame. </td></tr>
    <tr><td valign=top><em>percent</em>&nbsp;</td><td>Interpolation percentage.</td></tr>
  </table>
</dl>

<p>
Implements <a class="el" href="classaeModel.php#a2">aeModel</a>.    </td>
  </tr>
</table>
<a name="a2" doxytag="aeMD2Object::Draw"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> void aeMD2Object::Draw </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top"><a class="el" href="structaeEngineflags.php">aeEngineflags</a> *&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap><code> [virtual]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Draw the model.
<p>
This is called by <a class="el" href="classaeEngine.php#a8">aeEngine::Render()</a>. You shouldn't need to call this yourself.
<p>
Implements <a class="el" href="classaeModel.php#a1">aeModel</a>.    </td>
  </tr>
</table>
<a name="a7" doxytag="aeMD2Object::GetState"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> <a class="el" href="group__mdlldrstructs.php#a0">modelState_t</a> aeMD2Object::GetState </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap><code> [virtual]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Retrieve animation state for the model.
<p>
<dl compact><dt><b>Returns:</b></dt><dd>The animation state.</dd></dl>

<p>
Implements <a class="el" href="classaeModel.php#a6">aeModel</a>.    </td>
  </tr>
</table>
<a name="a4" doxytag="aeMD2Object::RenderFrame"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> int aeMD2Object::RenderFrame </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top"><a class="el" href="structaeEngineflags.php">aeEngineflags</a> *&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap><code> [virtual]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Render a single frame of the model.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>keyFrame</em>&nbsp;</td><td>The frame number.</td></tr>
  </table>
</dl>

<p>
Implements <a class="el" href="classaeModel.php#a3">aeModel</a>.    </td>
  </tr>
</table>
<a name="a5" doxytag="aeMD2Object::SetAnimation"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> void aeMD2Object::SetAnimation </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">int&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>startframe</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>int&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>endframe</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>float&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>percent</em></td>
        </tr>
        <tr>
          <td></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [virtual]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Set model animation given start frame, end frame, and interpolation percentage.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>startframe</em>&nbsp;</td><td>Start frame for animation. </td></tr>
    <tr><td valign=top><em>endframe</em>&nbsp;</td><td>End frame for animation </td></tr>
    <tr><td valign=top><em>interpol</em>&nbsp;</td><td>Interpolation percentage.</td></tr>
  </table>
</dl>

<p>
Implements <a class="el" href="classaeModel.php#a4">aeModel</a>.    </td>
  </tr>
</table>
<a name="a6" doxytag="aeMD2Object::SetFrame"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> void aeMD2Object::SetFrame </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">int&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp; <em>keyframe</em>          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap><code> [virtual]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Set model frame to render.
<p>
This will render a single still frame of a model.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>keyframe</em>&nbsp;</td><td>Frame of model to render.</td></tr>
  </table>
</dl>

<p>
Implements <a class="el" href="classaeModel.php#a5">aeModel</a>.    </td>
  </tr>
</table>
<a name="a8" doxytag="aeMD2Object::SetState"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> void aeMD2Object::SetState </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top"><a class="el" href="group__mdlldrstructs.php#a0">modelState_t</a>&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp; <em>state</em>          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap><code> [virtual]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Set the animation state for the model.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>state</em>&nbsp;</td><td>Animation state.</td></tr>
  </table>
</dl>

<p>
Implements <a class="el" href="classaeModel.php#a7">aeModel</a>.    </td>
  </tr>
</table>
<hr>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="md2object_8h-source.php">md2object.h</a></ul>
<hr><address style="align: right;"><small>Generated on Sun Mar 2 01:14:23 2003 for AE Engine by
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border=0 
width=110 height=53></a>1.3-rc2 </small></address>
</body>
</html>
