<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>Member List</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.3-rc2 -->
<center>
<a class="qindex" href="index.php">Main Page</a> &nbsp; <a class="qindex" href="modules.php">Modules</a> &nbsp; <a class="qindex" href="hierarchy.php">Class Hierarchy</a> &nbsp; <a class="qindex" href="classes.php">Alphabetical List</a> &nbsp; <a class="qindex" href="annotated.php">Compound List</a> &nbsp; <a class="qindex" href="files.php">File List</a> &nbsp; <a class="qindex" href="functions.php">Compound Members</a> &nbsp; </center>
<hr><h1>aeVector3 Member List</h1>This is the complete list of members for <a class="el" href="classaeVector3.php">aeVector3</a>, including all inherited members.<table>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#a0">aeVector3</a>()</td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#a1">aeVector3</a>(float nx, float ny, float nz=0)</td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td><code> [inline]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#a2">aeVector3</a>(const aeVector3 &amp;v)</td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td><code> [inline]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#a14">Cross</a>(const aeVector3 &amp;v1, const aeVector3 &amp;v2)</td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#a15">Magnitude</a>() const</td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#a17">Normalize</a>() const</td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#l2">operator *</a>(const aeVector3 &amp;v1, const aeVector3 &amp;v2)</td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td><code> [friend]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#l4">operator *</a>(const aeVector3 &amp;v1, float s)</td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td><code> [friend]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#l5">operator *</a>(float s, const aeVector3 &amp;v1)</td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td><code> [friend]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#l6">operator *</a>(int s, const aeVector3 &amp;v1)</td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td><code> [friend]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#a8">operator *=</a>(float s)</td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td><code> [inline]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#l10">operator!=</a>(const aeVector3 &amp;v1, const aeVector3 &amp;v2)</td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td><code> [friend]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#l3">operator%</a>(const aeVector3 &amp;v1, const aeVector3 &amp;v2)</td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td><code> [friend]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#l0">operator+</a>(const aeVector3 &amp;v1, const aeVector3 &amp;v2)</td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td><code> [friend]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#a10">operator+</a>() const</td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td><code> [inline]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#a6">operator+=</a>(const aeVector3 &amp;v1)</td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td><code> [inline]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#l1">operator-</a>(const aeVector3 &amp;v1, const aeVector3 &amp;v2)</td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td><code> [friend]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#a11">operator-</a>() const</td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td><code> [inline]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#a7">operator-=</a>(const aeVector3 &amp;v1)</td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td><code> [inline]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#l7">operator/</a>(const aeVector3 &amp;v1, float s)</td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td><code> [friend]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#l8">operator/</a>(const aeVector3 &amp;v1, int s)</td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td><code> [friend]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#a9">operator/=</a>(float s)</td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td><code> [inline]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#l9">operator==</a>(const aeVector3 &amp;v1, const aeVector3 &amp;v2)</td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td><code> [friend]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#a4">operator[]</a>(int n) const</td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td><code> [inline]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#a5">operator[]</a>(int n)</td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td><code> [inline]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#a12">Set</a>(float nx, float ny, float nz)</td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td><code> [inline]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#a13">Set</a>(const aeVector3 &amp;v)</td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td><code> [inline]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#a16">Unit</a>() const</td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td><code> [inline]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#m0">x</a></td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#m1">y</a></td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector3.php#m2">z</a></td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td><b>~aeVector3</b>() (defined in <a class="el" href="classaeVector3.php">aeVector3</a>)</td><td><a class="el" href="classaeVector3.php">aeVector3</a></td><td><code> [inline]</code></td></tr>
</table><hr><address style="align: right;"><small>Generated on Sun Mar 2 01:14:24 2003 for AE Engine by
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border=0 
width=110 height=53></a>1.3-rc2 </small></address>
</body>
</html>
