<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>aeEngine class Reference</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.3-rc2 -->
<center>
<a class="qindex" href="index.php">Main Page</a> &nbsp; <a class="qindex" href="modules.php">Modules</a> &nbsp; <a class="qindex" href="hierarchy.php">Class Hierarchy</a> &nbsp; <a class="qindex" href="classes.php">Alphabetical List</a> &nbsp; <a class="qindex" href="annotated.php">Compound List</a> &nbsp; <a class="qindex" href="files.php">File List</a> &nbsp; <a class="qindex" href="functions.php">Compound Members</a> &nbsp; </center>
<hr><h1>aeEngine Class Reference</h1>Interface to the engine. 
<a href="#_details">More...</a>
<p>
<code>#include &lt;<a class="el" href="engine_8h-source.php">engine.h</a>&gt;</code>
<p>
<p>Inheritance diagram for aeEngine:
<p><center><img src="classaeEngine.png" usemap="#aeEngine_map" border="0" alt=""></center>
<map name="aeEngine_map">
<area href="classaeBase.php" alt="aeBase" shape="rect" coords="0,0,65,24">
</map>
<a href="classaeEngine-members.php">List of all members.</a><table border=0 cellpadding=0 cellspacing=0>
<tr><td></td></tr>
<tr><td colspan=2><br><h2>Public Methods</h2></td></tr>
<tr><td nowrap align=right valign=top><a name="a0" doxytag="aeEngine::aeEngine"></a>
&nbsp;</td><td valign=bottom><b>aeEngine</b> (<a class="el" href="classaeRegistry.php">aeRegistry</a> *aeReg, int width, int height, int vidflags)</td></tr>
<tr><td nowrap align=right valign=top>void&nbsp;</td><td valign=bottom><a class="el" href="classaeEngine.php#a2">InitGL</a> ()</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Initialize OpenGL.</em> <a href="#a2"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>bool&nbsp;</td><td valign=bottom><a class="el" href="classaeEngine.php#a3">OpenApplication</a> ()</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Initialize and open a window.</em> <a href="#a3"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>int&nbsp;</td><td valign=bottom><a class="el" href="classaeEngine.php#a4">GetScreenWidth</a> () const</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Get the screen width.</em> <a href="#a4"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>int&nbsp;</td><td valign=bottom><a class="el" href="classaeEngine.php#a5">GetScreenHeight</a> () const</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Get the screen height.</em> <a href="#a5"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top><a class="el" href="classaeCamera.php">aeCamera</a> *&nbsp;</td><td valign=bottom><a class="el" href="classaeEngine.php#a6">GetCamera</a> () const</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Get the camera.</em> <a href="#a6"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>bool&nbsp;</td><td valign=bottom><a class="el" href="classaeEngine.php#a7">ResizeWindow</a> (int new_width, int new_height)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Resize the window.</em> <a href="#a7"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>void&nbsp;</td><td valign=bottom><a class="el" href="classaeEngine.php#a8">Render</a> ()</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Render the screen.</em> <a href="#a8"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>bool&nbsp;</td><td valign=bottom><a class="el" href="classaeEngine.php#a9">DefaultRunLoop</a> ()</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Enter the default runloop.</em> <a href="#a9"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>void&nbsp;</td><td valign=bottom><a class="el" href="classaeEngine.php#a10">AddObject</a> (<a class="el" href="classaeObject.php">aeObject</a> *)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Add an object to the engine.</em> <a href="#a10"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>void&nbsp;</td><td valign=bottom><a class="el" href="classaeEngine.php#a11">RegisterEventHandler</a> (<a class="el" href="group__eventstructs.php#a1">aeEventHandlerCallback</a>)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Register a event handler callback function.</em> <a href="#a11"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>void&nbsp;</td><td valign=bottom><a class="el" href="classaeEngine.php#a12">AttachCamera</a> (<a class="el" href="classaeCamera.php">aeCamera</a> *)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Attach a camera to the engine.</em> <a href="#a12"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>void&nbsp;</td><td valign=bottom><a class="el" href="classaeEngine.php#a13">ToggleFullScreen</a> ()</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Toggle fullscreen on/off.</em> <a href="#a13"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top><a class="el" href="classaeObject.php">aeObject</a> *&nbsp;</td><td valign=bottom><a class="el" href="classaeEngine.php#a14">FindObject</a> (unsigned int)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Find object by ID.</em> <a href="#a14"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top><a class="el" href="classaeObject.php">aeObject</a> *&nbsp;</td><td valign=bottom><a class="el" href="classaeEngine.php#a15">FindObjectByName</a> (char *)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Find object by name.</em> <a href="#a15"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>unsigned int&nbsp;</td><td valign=bottom><a class="el" href="classaeEngine.php#a16">GetObjectCount</a> ()</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Get the number of objects in the engine.</em> <a href="#a16"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top><a class="el" href="classaeTexture.php">aeTexture</a> *&nbsp;</td><td valign=bottom><a class="el" href="classaeEngine.php#a17">FindTexture</a> (unsigned int)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Find texture by ID.</em> <a href="#a17"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top><a class="el" href="classaeTexture.php">aeTexture</a> *&nbsp;</td><td valign=bottom><a class="el" href="classaeEngine.php#a18">FindTextureByName</a> (char *)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Find texture by name.</em> <a href="#a18"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>unsigned int&nbsp;</td><td valign=bottom><a class="el" href="classaeEngine.php#a19">GetTextureCount</a> ()</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Get the number of textures in the engine.</em> <a href="#a19"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top><a name="a20" doxytag="aeEngine::TempQuit"></a>
void&nbsp;</td><td valign=bottom><b>TempQuit</b> ()</td></tr>
<tr><td colspan=2><br><h2>Static Public Attributes</h2></td></tr>
<tr><td nowrap align=right valign=top><a name="p0" doxytag="aeEngine::self_ptr"></a>
aeEngine *&nbsp;</td><td valign=bottom><a class="el" href="classaeEngine.php#p0">self_ptr</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Global engine pointer.</em></font><br><br></td></tr>
</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
Interface to the engine.
<p>
This is the main interface to the AE 3D engine. 
<p>

<p>
Definition at line <a class="el" href="engine_8h-source.php#l00044">44</a> of file <a class="el" href="engine_8h-source.php">engine.h</a>.<hr><h2>Member Function Documentation</h2>
<a name="a10" doxytag="aeEngine::AddObject"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> void aeEngine::AddObject </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top"><a class="el" href="classaeObject.php">aeObject</a> *&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Add an object to the engine.
<p>
You should only use this when you create your own geometry with e.g. <a class="el" href="classaePolygon.php">aePolygon</a> or <a class="el" href="classaeTriangle.php">aeTriangle</a>. You do not need to add geometry loaded with e.g. the model loader plugin or the terrain plugin because the plugin will take care of that.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>aeObject</em>&nbsp;</td><td>* The object to add. </td></tr>
  </table>
</dl>
<dl compact><dt><b>See also:</b></dt><dd><a class="el" href="classaeLine.php">aeLine</a>, <a class="el" href="classaePolygon.php">aePolygon</a>, <a class="el" href="classaeTriangle.php">aeTriangle</a>, <a class="el" href="classaeQuad.php">aeQuad</a></dd></dl>
    </td>
  </tr>
</table>
<a name="a12" doxytag="aeEngine::AttachCamera"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> void aeEngine::AttachCamera </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top"><a class="el" href="classaeCamera.php">aeCamera</a> *&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Attach a camera to the engine.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>aeCamera</em>&nbsp;</td><td>* A camera object.</td></tr>
  </table>
</dl>
    </td>
  </tr>
</table>
<a name="a9" doxytag="aeEngine::DefaultRunLoop"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> bool aeEngine::DefaultRunLoop </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Enter the default runloop.
<p>
Usually you call this after all other initialization to enter the default runloop.
<p>
<dl compact><dt><b>Returns:</b></dt><dd>True if the runloop was exited normally, false if not.</dd></dl>
    </td>
  </tr>
</table>
<a name="a14" doxytag="aeEngine::FindObject"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> <a class="el" href="classaeObject.php">aeObject</a>* aeEngine::FindObject </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">unsigned&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp; <em>int</em>          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Find object by ID.
<p>
This is only a wrapper around <a class="el" href="classaeRegistry.php#a7">aeRegistry::FindObject()</a>.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>int</em>&nbsp;</td><td>Object ID to query.</td></tr>
  </table>
</dl>
<dl compact><dt><b>Returns:</b></dt><dd>The object, or NULL if it's not found.</dd></dl>
    </td>
  </tr>
</table>
<a name="a15" doxytag="aeEngine::FindObjectByName"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> <a class="el" href="classaeObject.php">aeObject</a>* aeEngine::FindObjectByName </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">char *&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Find object by name.
<p>
This is only a wrapper around <a class="el" href="classaeRegistry.php#a8">aeRegistry::FindObjectByName()</a>.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>char</em>&nbsp;</td><td>* Object name.</td></tr>
  </table>
</dl>
<dl compact><dt><b>Returns:</b></dt><dd>The object, or NULL if it's not found.</dd></dl>
    </td>
  </tr>
</table>
<a name="a17" doxytag="aeEngine::FindTexture"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> <a class="el" href="classaeTexture.php">aeTexture</a>* aeEngine::FindTexture </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">unsigned&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp; <em>int</em>          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Find texture by ID.
<p>
This is only a wrapper around <a class="el" href="classaeRegistry.php#a10">aeRegistry::FindTexture()</a>.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>int</em>&nbsp;</td><td>Texture ID to query.</td></tr>
  </table>
</dl>
<dl compact><dt><b>Returns:</b></dt><dd>The texture object, or NULL if it's not found.</dd></dl>
    </td>
  </tr>
</table>
<a name="a18" doxytag="aeEngine::FindTextureByName"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> <a class="el" href="classaeTexture.php">aeTexture</a>* aeEngine::FindTextureByName </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">char *&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Find texture by name.
<p>
This is only a wrapper around <a class="el" href="classaeRegistry.php#a11">aeRegistry::FindTextureByName()</a>.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>char</em>&nbsp;</td><td>* Texture name.</td></tr>
  </table>
</dl>
<dl compact><dt><b>Returns:</b></dt><dd>The texture object, or NULL if it's not found.</dd></dl>
    </td>
  </tr>
</table>
<a name="a6" doxytag="aeEngine::GetCamera"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> <a class="el" href="classaeCamera.php">aeCamera</a>* aeEngine::GetCamera </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap> const<code> [inline]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Get the camera.
<p>
You must call <a class="el" href="classaeEngine.php#a12">AttachCamera()</a> first to attach a camera.
<p>
<dl compact><dt><b>Returns:</b></dt><dd>The camera object.</dd></dl>

<p>
Definition at line <a class="el" href="engine_8h-source.php#l00116">116</a> of file <a class="el" href="engine_8h-source.php">engine.h</a>.    </td>
  </tr>
</table>
<a name="a16" doxytag="aeEngine::GetObjectCount"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> unsigned int aeEngine::GetObjectCount </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Get the number of objects in the engine.
<p>
This is only a wrapper around aeRegistry::NumObjects().
<p>
<dl compact><dt><b>Returns:</b></dt><dd>The number of objects.</dd></dl>
    </td>
  </tr>
</table>
<a name="a5" doxytag="aeEngine::GetScreenHeight"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> int aeEngine::GetScreenHeight </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap> const<code> [inline]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Get the screen height.
<p>
<dl compact><dt><b>Returns:</b></dt><dd>The screen height.</dd></dl>

<p>
Definition at line <a class="el" href="engine_8h-source.php#l00107">107</a> of file <a class="el" href="engine_8h-source.php">engine.h</a>.    </td>
  </tr>
</table>
<a name="a4" doxytag="aeEngine::GetScreenWidth"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> int aeEngine::GetScreenWidth </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap> const<code> [inline]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Get the screen width.
<p>
<dl compact><dt><b>Returns:</b></dt><dd>The screen width.</dd></dl>

<p>
Definition at line <a class="el" href="engine_8h-source.php#l00099">99</a> of file <a class="el" href="engine_8h-source.php">engine.h</a>.    </td>
  </tr>
</table>
<a name="a19" doxytag="aeEngine::GetTextureCount"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> unsigned int aeEngine::GetTextureCount </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Get the number of textures in the engine.
<p>
This is only a wrapper around aeRegistry::NumTextures().
<p>
<dl compact><dt><b>Returns:</b></dt><dd>The number of textures.</dd></dl>
    </td>
  </tr>
</table>
<a name="a2" doxytag="aeEngine::InitGL"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> void aeEngine::InitGL </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Initialize OpenGL.
<p>
This is called automagically in <a class="el" href="classaeEngine.php#a3">OpenApplication()</a>.
<p>
<dl compact><dt><b>Returns:</b></dt><dd>True if OpenGL could be initialized, and false on error.</dd></dl>
    </td>
  </tr>
</table>
<a name="a3" doxytag="aeEngine::OpenApplication"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> bool aeEngine::OpenApplication </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Initialize and open a window.
<p>
<dl compact><dt><b>Returns:</b></dt><dd>True if window was created succesfully, false if not.</dd></dl>
    </td>
  </tr>
</table>
<a name="a11" doxytag="aeEngine::RegisterEventHandler"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> void aeEngine::RegisterEventHandler </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top"><a class="el" href="group__eventstructs.php#a1">aeEventHandlerCallback</a>&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Register a event handler callback function.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>aeEventHandlerCallback</em>&nbsp;</td><td>Static event handler callback function.</td></tr>
  </table>
</dl>
    </td>
  </tr>
</table>
<a name="a8" doxytag="aeEngine::Render"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> void aeEngine::Render </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Render the screen.
<p>
You must call this upon aeevProcessFrame to get anything drawn on the screen.    </td>
  </tr>
</table>
<a name="a7" doxytag="aeEngine::ResizeWindow"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> bool aeEngine::ResizeWindow </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">int&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>new_width</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>int&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>new_height</em></td>
        </tr>
        <tr>
          <td></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Resize the window.
<p>
This should be called upon aeevResize event to resize the window.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>new_width</em>&nbsp;</td><td>New window width. </td></tr>
    <tr><td valign=top><em>new_height</em>&nbsp;</td><td>New window height.</td></tr>
  </table>
</dl>
<dl compact><dt><b>Returns:</b></dt><dd>True if the window was resized succesfully, false if not.</dd></dl>
    </td>
  </tr>
</table>
<a name="a13" doxytag="aeEngine::ToggleFullScreen"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> void aeEngine::ToggleFullScreen </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Toggle fullscreen on/off.
<p>
    </td>
  </tr>
</table>
<hr>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="engine_8h-source.php">engine.h</a></ul>
<hr><address style="align: right;"><small>Generated on Sun Mar 2 01:14:23 2003 for AE Engine by
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border=0 
width=110 height=53></a>1.3-rc2 </small></address>
</body>
</html>
