<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>aeSystem class Reference</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.3-rc2 -->
<center>
<a class="qindex" href="index.php">Main Page</a> &nbsp; <a class="qindex" href="modules.php">Modules</a> &nbsp; <a class="qindex" href="hierarchy.php">Class Hierarchy</a> &nbsp; <a class="qindex" href="classes.php">Alphabetical List</a> &nbsp; <a class="qindex" href="annotated.php">Compound List</a> &nbsp; <a class="qindex" href="files.php">File List</a> &nbsp; <a class="qindex" href="functions.php">Compound Members</a> &nbsp; </center>
<hr><h1>aeSystem Class Reference</h1>This class is an interface to the operating system and the window manager. 
<a href="#_details">More...</a>
<p>
<code>#include &lt;<a class="el" href="system_8h-source.php">system.h</a>&gt;</code>
<p>
<p>Inheritance diagram for aeSystem:
<p><center><img src="classaeSystem.png" usemap="#aeSystem_map" border="0" alt=""></center>
<map name="aeSystem_map">
<area href="classaeBase.php" alt="aeBase" shape="rect" coords="0,0,66,24">
</map>
<a href="classaeSystem-members.php">List of all members.</a><table border=0 cellpadding=0 cellspacing=0>
<tr><td></td></tr>
<tr><td colspan=2><br><h2>Public Methods</h2></td></tr>
<tr><td nowrap align=right valign=top><a name="a0" doxytag="aeSystem::aeSystem"></a>
&nbsp;</td><td valign=bottom><b>aeSystem</b> (<a class="el" href="classaeRegistry.php">aeRegistry</a> *registry)</td></tr>
<tr><td nowrap align=right valign=top>void&nbsp;</td><td valign=bottom><a class="el" href="classaeSystem.php#a2">SetWindowCaption</a> (char *icon, char *caption,...)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Set the window caption and icon name.</em> <a href="#a2"></a><em></em></font><br><br></td></tr>
</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
This class is an interface to the operating system and the window manager.
<p>

<p>
Definition at line <a class="el" href="system_8h-source.php#l00037">37</a> of file <a class="el" href="system_8h-source.php">system.h</a>.<hr><h2>Member Function Documentation</h2>
<a name="a2" doxytag="aeSystem::SetWindowCaption"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> void aeSystem::SetWindowCaption </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">char *&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>icon</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>char *&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>caption</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>...&nbsp;</td>
          <td class="mdname" nowrap>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Set the window caption and icon name.
<p>
Window caption also accepts format characters (just like printf), so you can e.g. call SetWindowCaption("myapp", "FPS: f", engine-&gt;GetFPS()).
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>icon</em>&nbsp;</td><td>Icon name. </td></tr>
    <tr><td valign=top><em>caption</em>&nbsp;</td><td>Window title bar text. </td></tr>
    <tr><td valign=top><em>...</em>&nbsp;</td><td>Any printf-type format variables.</td></tr>
  </table>
</dl>
    </td>
  </tr>
</table>
<hr>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="system_8h-source.php">system.h</a></ul>
<hr><address style="align: right;"><small>Generated on Sun Mar 2 01:14:23 2003 for AE Engine by
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border=0 
width=110 height=53></a>1.3-rc2 </small></address>
</body>
</html>
