<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>aeObject class Reference</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.3-rc2 -->
<center>
<a class="qindex" href="index.php">Main Page</a> &nbsp; <a class="qindex" href="modules.php">Modules</a> &nbsp; <a class="qindex" href="hierarchy.php">Class Hierarchy</a> &nbsp; <a class="qindex" href="classes.php">Alphabetical List</a> &nbsp; <a class="qindex" href="annotated.php">Compound List</a> &nbsp; <a class="qindex" href="files.php">File List</a> &nbsp; <a class="qindex" href="functions.php">Compound Members</a> &nbsp; </center>
<hr><h1>aeObject Class Reference</h1>A base class for all objects. 
<a href="#_details">More...</a>
<p>
<code>#include &lt;<a class="el" href="object_8h-source.php">object.h</a>&gt;</code>
<p>
<p>Inheritance diagram for aeObject:
<p><center><img src="classaeObject.png" usemap="#aeObject_map" border="0" alt=""></center>
<map name="aeObject_map">
<area href="classaeBase.php" alt="aeBase" shape="rect" coords="200,0,290,24">
<area href="classaeLine.php" alt="aeLine" shape="rect" coords="0,112,90,136">
<area href="classaeModel.php" alt="aeModel" shape="rect" coords="100,112,190,136">
<area href="classaePolygon.php" alt="aePolygon" shape="rect" coords="200,112,290,136">
<area href="classaeQuad.php" alt="aeQuad" shape="rect" coords="300,112,390,136">
<area href="classaeTriangle.php" alt="aeTriangle" shape="rect" coords="400,112,490,136">
<area href="classaeMD2Object.php" alt="aeMD2Object" shape="rect" coords="100,168,190,192">
</map>
<a href="classaeObject-members.php">List of all members.</a><table border=0 cellpadding=0 cellspacing=0>
<tr><td></td></tr>
<tr><td colspan=2><br><h2>Public Methods</h2></td></tr>
<tr><td nowrap align=right valign=top>virtual char *&nbsp;</td><td valign=bottom><a class="el" href="classaeObject.php#a1">GetName</a> ()</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Get object's name.</em> <a href="#a1"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>virtual <a class="el" href="classaeMaterial.php">aeMaterial</a> *&nbsp;</td><td valign=bottom><a class="el" href="classaeObject.php#a2">GetMaterial</a> ()</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Get the object's material.</em> <a href="#a2"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>virtual void&nbsp;</td><td valign=bottom><a class="el" href="classaeObject.php#a3">Draw</a> (<a class="el" href="structaeEngineflags.php">aeEngineflags</a> *)=0</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Draw this object.</em> <a href="#a3"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>virtual <a class="el" href="classaeVector3.php">aeVector3</a>&nbsp;</td><td valign=bottom><a class="el" href="classaeObject.php#a4">GetOrigin</a> ()</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Get the origin for this object.</em> <a href="#a4"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>virtual void&nbsp;</td><td valign=bottom><a class="el" href="classaeObject.php#a5">SetOrigin</a> (const <a class="el" href="classaeVector3.php">aeVector3</a> &amp;norigin)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Set the origin for this object.</em> <a href="#a5"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>virtual void&nbsp;</td><td valign=bottom><a class="el" href="classaeObject.php#a6">SetColor</a> (float r, float g, float b)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Set the RGB color of this object.</em> <a href="#a6"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>virtual void&nbsp;</td><td valign=bottom><a class="el" href="classaeObject.php#a7">SetColor</a> (float r, float g, float b, float a)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Set the RGBA color of this object.</em> <a href="#a7"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>virtual void&nbsp;</td><td valign=bottom><a class="el" href="classaeObject.php#a8">SetColor</a> (const <a class="el" href="classaeColor3.php">aeColor3</a> &amp;color)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Set the RGB color of this object.</em> <a href="#a8"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>virtual void&nbsp;</td><td valign=bottom><a class="el" href="classaeObject.php#a9">SetColor</a> (const <a class="el" href="classaeColor4.php">aeColor4</a> &amp;color)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Set the RGBA color of this object.</em> <a href="#a9"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>virtual void&nbsp;</td><td valign=bottom><a class="el" href="classaeObject.php#a10">SetTexCoord</a> (const <a class="el" href="classaeTexCoord2.php">aeTexCoord2</a> &amp;texcoord)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Set the texture coordinate for the next vertex(es).</em> <a href="#a10"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>virtual void&nbsp;</td><td valign=bottom><a class="el" href="classaeObject.php#a11">SetTexCoord</a> (float s, float t)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Set the texture coordinate for the next vertex(es).</em> <a href="#a11"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>virtual void&nbsp;</td><td valign=bottom><a class="el" href="classaeObject.php#a12">SetMaterial</a> (<a class="el" href="classaeMaterial.php">aeMaterial</a> *mat)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Set material for this object.</em> <a href="#a12"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>virtual void&nbsp;</td><td valign=bottom><a class="el" href="classaeObject.php#a13">AddVertex</a> (const <a class="el" href="classaeVector3.php">aeVector3</a> &amp;vertex)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Add a vertex to this object.</em> <a href="#a13"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>virtual void&nbsp;</td><td valign=bottom><a class="el" href="classaeObject.php#a14">SetTransparent</a> (bool)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Used to specify whether this object is transparent or not.</em> <a href="#a14"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>virtual unsigned int&nbsp;</td><td valign=bottom><a class="el" href="classaeObject.php#a15">GetVertexCount</a> ()</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Get the number of vertices in this object.</em> <a href="#a15"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>virtual <a class="el" href="classaeVector3.php">aeVector3</a>&nbsp;</td><td valign=bottom><a class="el" href="classaeObject.php#a16">GetVertex</a> (int)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Get a vertex of this object.</em> <a href="#a16"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>virtual float&nbsp;</td><td valign=bottom><a class="el" href="classaeObject.php#a17">GetBoundingSphereRadius</a> ()</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Return the radius of the bounding sphere of this object.</em> <a href="#a17"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>virtual bool&nbsp;</td><td valign=bottom><a class="el" href="classaeObject.php#a18">IsTransparent</a> ()</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Used to check if this object is currently transparent.</em> <a href="#a18"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>virtual void&nbsp;</td><td valign=bottom><a class="el" href="classaeObject.php#a19">SetMode</a> (<a class="el" href="group__aeObjRenderingModes.php#a0">aeObjRenderingMode</a> mode)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Set the object rendering mode.</em> <a href="#a19"></a><em></em></font><br><br></td></tr>
<tr><td colspan=2><br><h2>Protected Attributes</h2></td></tr>
<tr><td nowrap align=right valign=top><a name="n0" doxytag="aeObject::vertexList"></a>
std::vector&lt; <a class="el" href="classaeVector3.php">aeVector3</a> &gt; *&nbsp;</td><td valign=bottom><b>vertexList</b></td></tr>
<tr><td nowrap align=right valign=top><a name="n1" doxytag="aeObject::vertexColorList"></a>
std::vector&lt; <a class="el" href="classaeColor4.php">aeColor4</a> &gt; *&nbsp;</td><td valign=bottom><b>vertexColorList</b></td></tr>
<tr><td nowrap align=right valign=top><a name="n2" doxytag="aeObject::vertexTexcoordList"></a>
std::vector&lt; <a class="el" href="classaeTexCoord2.php">aeTexCoord2</a> &gt; *&nbsp;</td><td valign=bottom><b>vertexTexcoordList</b></td></tr>
<tr><td nowrap align=right valign=top><a name="n3" doxytag="aeObject::origin"></a>
<a class="el" href="classaeVector3.php">aeVector3</a>&nbsp;</td><td valign=bottom><b>origin</b></td></tr>
<tr><td nowrap align=right valign=top><a name="n4" doxytag="aeObject::currentVertexColor"></a>
<a class="el" href="classaeColor4.php">aeColor4</a>&nbsp;</td><td valign=bottom><b>currentVertexColor</b></td></tr>
<tr><td nowrap align=right valign=top><a name="n5" doxytag="aeObject::currentVertexTexcoord"></a>
<a class="el" href="classaeTexCoord2.php">aeTexCoord2</a>&nbsp;</td><td valign=bottom><b>currentVertexTexcoord</b></td></tr>
<tr><td nowrap align=right valign=top><a name="n6" doxytag="aeObject::hasMaterial"></a>
bool&nbsp;</td><td valign=bottom><b>hasMaterial</b></td></tr>
<tr><td nowrap align=right valign=top><a name="n7" doxytag="aeObject::material"></a>
<a class="el" href="classaeMaterial.php">aeMaterial</a> *&nbsp;</td><td valign=bottom><b>material</b></td></tr>
<tr><td nowrap align=right valign=top><a name="n8" doxytag="aeObject::objName"></a>
char *&nbsp;</td><td valign=bottom><b>objName</b></td></tr>
<tr><td nowrap align=right valign=top><a name="n9" doxytag="aeObject::isTransparent"></a>
bool&nbsp;</td><td valign=bottom><b>isTransparent</b></td></tr>
<tr><td nowrap align=right valign=top><a name="n10" doxytag="aeObject::objRadius"></a>
float&nbsp;</td><td valign=bottom><b>objRadius</b></td></tr>
<tr><td nowrap align=right valign=top><a name="n11" doxytag="aeObject::objRenderMode"></a>
<a class="el" href="group__aeObjRenderingModes.php#a0">aeObjRenderingMode</a>&nbsp;</td><td valign=bottom><b>objRenderMode</b></td></tr>
</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
A base class for all objects.
<p>

<p>
Definition at line <a class="el" href="object_8h-source.php#l00129">129</a> of file <a class="el" href="object_8h-source.php">object.h</a>.<hr><h2>Member Function Documentation</h2>
<a name="a13" doxytag="aeObject::AddVertex"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> virtual void aeObject::AddVertex </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">const <a class="el" href="classaeVector3.php">aeVector3</a> &amp;&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp; <em>vertex</em>          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap><code> [virtual]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Add a vertex to this object.
<p>
This adds a single vertex to this object.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>vertex</em>&nbsp;</td><td>The vertex vector.</td></tr>
  </table>
</dl>
    </td>
  </tr>
</table>
<a name="a3" doxytag="aeObject::Draw"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> virtual void aeObject::Draw </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top"><a class="el" href="structaeEngineflags.php">aeEngineflags</a> *&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap><code> [pure virtual]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Draw this object.
<p>
This is called by <a class="el" href="classaeEngine.php#a8">aeEngine::Render()</a>. You shouldn't need to call this yourself.
<p>
Implemented in <a class="el" href="classaeLine.php#a3">aeLine</a>, <a class="el" href="classaeModel.php#a1">aeModel</a>, <a class="el" href="classaePolygon.php#a3">aePolygon</a>, <a class="el" href="classaeQuad.php#a3">aeQuad</a>, <a class="el" href="classaeTriangle.php#a3">aeTriangle</a>, and <a class="el" href="classaeMD2Object.php#a2">aeMD2Object</a>.    </td>
  </tr>
</table>
<a name="a17" doxytag="aeObject::GetBoundingSphereRadius"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> virtual float aeObject::GetBoundingSphereRadius </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap><code> [virtual]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Return the radius of the bounding sphere of this object.
<p>
<dl compact><dt><b>Returns:</b></dt><dd>Bounding sphere radius of this object.</dd></dl>
    </td>
  </tr>
</table>
<a name="a2" doxytag="aeObject::GetMaterial"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> virtual <a class="el" href="classaeMaterial.php">aeMaterial</a>* aeObject::GetMaterial </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap><code> [virtual]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Get the object's material.
<p>
<dl compact><dt><b>Returns:</b></dt><dd>The object's material.</dd></dl>
    </td>
  </tr>
</table>
<a name="a1" doxytag="aeObject::GetName"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> virtual char* aeObject::GetName </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap><code> [virtual]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Get object's name.
<p>
<dl compact><dt><b>Returns:</b></dt><dd>The object's name.</dd></dl>
    </td>
  </tr>
</table>
<a name="a4" doxytag="aeObject::GetOrigin"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> virtual <a class="el" href="classaeVector3.php">aeVector3</a> aeObject::GetOrigin </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap><code> [virtual]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Get the origin for this object.
<p>
<dl compact><dt><b>Returns:</b></dt><dd>The object's origin.</dd></dl>
    </td>
  </tr>
</table>
<a name="a16" doxytag="aeObject::GetVertex"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> virtual <a class="el" href="classaeVector3.php">aeVector3</a> aeObject::GetVertex </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">int&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap><code> [virtual]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Get a vertex of this object.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>int</em>&nbsp;</td><td>The vertex index number.</td></tr>
  </table>
</dl>
<dl compact><dt><b>Returns:</b></dt><dd>The vertex.</dd></dl>
    </td>
  </tr>
</table>
<a name="a15" doxytag="aeObject::GetVertexCount"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> virtual unsigned int aeObject::GetVertexCount </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap><code> [virtual]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Get the number of vertices in this object.
<p>
<dl compact><dt><b>Returns:</b></dt><dd>The vertex count of this object.</dd></dl>
    </td>
  </tr>
</table>
<a name="a18" doxytag="aeObject::IsTransparent"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> virtual bool aeObject::IsTransparent </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap><code> [virtual]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Used to check if this object is currently transparent.
<p>
<dl compact><dt><b>Returns:</b></dt><dd>True if the object is transparent, false if not.</dd></dl>
    </td>
  </tr>
</table>
<a name="a9" doxytag="aeObject::SetColor"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> virtual void aeObject::SetColor </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">const <a class="el" href="classaeColor4.php">aeColor4</a> &amp;&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp; <em>color</em>          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap><code> [virtual]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Set the RGBA color of this object.
<p>
This accepts an <a class="el" href="classaeColor4.php">aeColor4</a> to specify the color. Subsequent <a class="el" href="classaeObject.php#a13">AddVertex()</a> calls will add a vertex of this color.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>color</em>&nbsp;</td><td>an <a class="el" href="classaeColor4.php">aeColor4</a> instance representing the wanted color.</td></tr>
  </table>
</dl>
    </td>
  </tr>
</table>
<a name="a8" doxytag="aeObject::SetColor"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> virtual void aeObject::SetColor </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">const <a class="el" href="classaeColor3.php">aeColor3</a> &amp;&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp; <em>color</em>          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap><code> [virtual]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Set the RGB color of this object.
<p>
This accepts an <a class="el" href="classaeColor3.php">aeColor3</a> to specify the color. Subsequent <a class="el" href="classaeObject.php#a13">AddVertex()</a> calls will add a vertex of this color.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>color</em>&nbsp;</td><td>an <a class="el" href="classaeColor3.php">aeColor3</a> instance representing the wanted color.</td></tr>
  </table>
</dl>
    </td>
  </tr>
</table>
<a name="a7" doxytag="aeObject::SetColor"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> virtual void aeObject::SetColor </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">float&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>r</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>float&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>g</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>float&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>b</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>float&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>a</em></td>
        </tr>
        <tr>
          <td></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [virtual]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Set the RGBA color of this object.
<p>
The values are from 0.0 to 1.0. Subsequent <a class="el" href="classaeObject.php#a13">AddVertex()</a> calls will add a vertex of this color.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>r</em>&nbsp;</td><td>Red. </td></tr>
    <tr><td valign=top><em>g</em>&nbsp;</td><td>Green. </td></tr>
    <tr><td valign=top><em>b</em>&nbsp;</td><td>Blue. </td></tr>
    <tr><td valign=top><em>a</em>&nbsp;</td><td>Alpha.</td></tr>
  </table>
</dl>
    </td>
  </tr>
</table>
<a name="a6" doxytag="aeObject::SetColor"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> virtual void aeObject::SetColor </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">float&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>r</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>float&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>g</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>float&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>b</em></td>
        </tr>
        <tr>
          <td></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [virtual]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Set the RGB color of this object.
<p>
The values are from 0.0 to 1.0. Subsequent <a class="el" href="classaeObject.php#a13">AddVertex()</a> calls will add a vertex of this color.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>r</em>&nbsp;</td><td>Red. </td></tr>
    <tr><td valign=top><em>g</em>&nbsp;</td><td>Green. </td></tr>
    <tr><td valign=top><em>b</em>&nbsp;</td><td>Blue.</td></tr>
  </table>
</dl>
    </td>
  </tr>
</table>
<a name="a12" doxytag="aeObject::SetMaterial"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> virtual void aeObject::SetMaterial </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top"><a class="el" href="classaeMaterial.php">aeMaterial</a> *&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp; <em>mat</em>          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap><code> [virtual]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Set material for this object.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>The</em>&nbsp;</td><td>material.</td></tr>
  </table>
</dl>
    </td>
  </tr>
</table>
<a name="a19" doxytag="aeObject::SetMode"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> virtual void aeObject::SetMode </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top"><a class="el" href="group__aeObjRenderingModes.php#a0">aeObjRenderingMode</a>&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp; <em>mode</em>          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap><code> [virtual]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Set the object rendering mode.
<p>
For each derived object type (<a class="el" href="classaeTriangle.php">aeTriangle</a>, <a class="el" href="classaeQuad.php">aeQuad</a>, <a class="el" href="classaePolygon.php">aePolygon</a>, <a class="el" href="classaeLine.php">aeLine</a>) there is a set of rendering modes which indicate how the object's vertices are to be interpreted when drawing them. Possible modes are:
<p>
<ul>
<li>
TRIANGLES_NORMAL </li>
<li>
TRIANGLES_STRIP </li>
<li>
TRIANGLES_FAN </li>
<li>
QUADS_NORMAL </li>
<li>
QUADS_STRIP </li>
<li>
LINES_NORMAL </li>
<li>
LINES_STRIP </li>
<li>
LINES_LOOP </li>
<li>
POLYGON_NORMAL </li>
</ul>

<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>mode</em>&nbsp;</td><td>The object rendering mode to use. </td></tr>
  </table>
</dl>
<dl compact><dt><b>See also:</b></dt><dd><a class="el" href="group__aeObjRenderingModes.php#a0">aeObjRenderingMode</a></dd></dl>
    </td>
  </tr>
</table>
<a name="a5" doxytag="aeObject::SetOrigin"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> virtual void aeObject::SetOrigin </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">const <a class="el" href="classaeVector3.php">aeVector3</a> &amp;&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp; <em>norigin</em>          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap><code> [virtual]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Set the origin for this object.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>o_origin</em>&nbsp;</td><td>The origin vector.</td></tr>
  </table>
</dl>
    </td>
  </tr>
</table>
<a name="a11" doxytag="aeObject::SetTexCoord"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> virtual void aeObject::SetTexCoord </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">float&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>s</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>float&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>t</em></td>
        </tr>
        <tr>
          <td></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [virtual]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Set the texture coordinate for the next vertex(es).
<p>
Use this before <a class="el" href="classaeObject.php#a13">AddVertex()</a> to add a texture coordinate for that vertex. If you set a texcoord only for the first vertex, that coordinate will be used for all subsequent vertices until you specify a new texture coordinate.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>s</em>&nbsp;</td><td>The s coordinate. </td></tr>
    <tr><td valign=top><em>t</em>&nbsp;</td><td>The t coordinate.</td></tr>
  </table>
</dl>
    </td>
  </tr>
</table>
<a name="a10" doxytag="aeObject::SetTexCoord"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> virtual void aeObject::SetTexCoord </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">const <a class="el" href="classaeTexCoord2.php">aeTexCoord2</a> &amp;&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp; <em>texcoord</em>          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap><code> [virtual]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Set the texture coordinate for the next vertex(es).
<p>
Use this before <a class="el" href="classaeObject.php#a13">AddVertex()</a> to add a texture coordinate for that vertex. If you set a texcoord only for the first vertex, that coordinate will be used for all subsequent vertices until you specify a new texture coordinate.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>texcoord</em>&nbsp;</td><td>a 2D texcoord representing the texture coordinate.</td></tr>
  </table>
</dl>
    </td>
  </tr>
</table>
<a name="a14" doxytag="aeObject::SetTransparent"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> virtual void aeObject::SetTransparent </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">bool&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap><code> [virtual]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Used to specify whether this object is transparent or not.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>bool</em>&nbsp;</td><td>true = transparent, false = solid (default).</td></tr>
  </table>
</dl>
    </td>
  </tr>
</table>
<hr>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="object_8h-source.php">object.h</a></ul>
<hr><address style="align: right;"><small>Generated on Sun Mar 2 01:14:23 2003 for AE Engine by
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border=0 
width=110 height=53></a>1.3-rc2 </small></address>
</body>
</html>
