<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>aeDataBuffer class Reference</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.3-rc2 -->
<center>
<a class="qindex" href="index.php">Main Page</a> &nbsp; <a class="qindex" href="modules.php">Modules</a> &nbsp; <a class="qindex" href="hierarchy.php">Class Hierarchy</a> &nbsp; <a class="qindex" href="classes.php">Alphabetical List</a> &nbsp; <a class="qindex" href="annotated.php">Compound List</a> &nbsp; <a class="qindex" href="files.php">File List</a> &nbsp; <a class="qindex" href="functions.php">Compound Members</a> &nbsp; </center>
<hr><h1>aeDataBuffer Class Reference</h1>A generic data buffer class. 
<a href="#_details">More...</a>
<p>
<code>#include &lt;<a class="el" href="databuffer_8h-source.php">databuffer.h</a>&gt;</code>
<p>
<p>Inheritance diagram for aeDataBuffer:
<p><center><img src="classaeDataBuffer.png" usemap="#aeDataBuffer_map" border="0" alt=""></center>
<map name="aeDataBuffer_map">
<area href="classaeBase.php" alt="aeBase" shape="rect" coords="0,0,87,24">
</map>
<a href="classaeDataBuffer-members.php">List of all members.</a><table border=0 cellpadding=0 cellspacing=0>
<tr><td></td></tr>
<tr><td colspan=2><br><h2>Public Methods</h2></td></tr>
<tr><td nowrap align=right valign=top><a name="a1" doxytag="aeDataBuffer::aeDataBuffer"></a>
&nbsp;</td><td valign=bottom><b>aeDataBuffer</b> (const char *dfile, bool binary=false)</td></tr>
<tr><td nowrap align=right valign=top>bool&nbsp;</td><td valign=bottom><a class="el" href="classaeDataBuffer.php#a3">Read</a> (const char *dfile, bool binary=false)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Read a file into the buffer.</em> <a href="#a3"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>char *&nbsp;</td><td valign=bottom><a class="el" href="classaeDataBuffer.php#a4">GetData</a> () const</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Get the data from the buffer.</em> <a href="#a4"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>size_t&nbsp;</td><td valign=bottom><a class="el" href="classaeDataBuffer.php#a5">GetSize</a> () const</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Get the size of the data in the buffer.</em> <a href="#a5"></a><em></em></font><br><br></td></tr>
</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
A generic data buffer class.
<p>

<p>
Definition at line <a class="el" href="databuffer_8h-source.php#l00034">34</a> of file <a class="el" href="databuffer_8h-source.php">databuffer.h</a>.<hr><h2>Member Function Documentation</h2>
<a name="a4" doxytag="aeDataBuffer::GetData"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> char* aeDataBuffer::GetData </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap> const<code> [inline]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Get the data from the buffer.
<p>
<dl compact><dt><b>Returns:</b></dt><dd>The data.</dd></dl>

<p>
Definition at line <a class="el" href="databuffer_8h-source.php#l00062">62</a> of file <a class="el" href="databuffer_8h-source.php">databuffer.h</a>.    </td>
  </tr>
</table>
<a name="a5" doxytag="aeDataBuffer::GetSize"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> size_t aeDataBuffer::GetSize </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap> const<code> [inline]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Get the size of the data in the buffer.
<p>
<dl compact><dt><b>Returns:</b></dt><dd>The data size.k</dd></dl>

<p>
Definition at line <a class="el" href="databuffer_8h-source.php#l00070">70</a> of file <a class="el" href="databuffer_8h-source.php">databuffer.h</a>.    </td>
  </tr>
</table>
<a name="a3" doxytag="aeDataBuffer::Read"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> bool aeDataBuffer::Read </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">const char *&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>dfile</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>bool&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>binary</em> = false</td>
        </tr>
        <tr>
          <td></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Read a file into the buffer.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>dfile</em>&nbsp;</td><td>Path to the file. </td></tr>
    <tr><td valign=top><em>binary</em>&nbsp;</td><td>Binary mode.</td></tr>
  </table>
</dl>
<dl compact><dt><b>Returns:</b></dt><dd>true if the file was read succesfully.</dd></dl>
    </td>
  </tr>
</table>
<hr>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="databuffer_8h-source.php">databuffer.h</a></ul>
<hr><address style="align: right;"><small>Generated on Sun Mar 2 01:14:23 2003 for AE Engine by
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border=0 
width=110 height=53></a>1.3-rc2 </small></address>
</body>
</html>
