<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>Member List</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.3-rc2 -->
<center>
<a class="qindex" href="index.php">Main Page</a> &nbsp; <a class="qindex" href="modules.php">Modules</a> &nbsp; <a class="qindex" href="hierarchy.php">Class Hierarchy</a> &nbsp; <a class="qindex" href="classes.php">Alphabetical List</a> &nbsp; <a class="qindex" href="annotated.php">Compound List</a> &nbsp; <a class="qindex" href="files.php">File List</a> &nbsp; <a class="qindex" href="functions.php">Compound Members</a> &nbsp; </center>
<hr><h1>aeVector Member List</h1>This is the complete list of members for <a class="el" href="classaeVector.php">aeVector</a>, including all inherited members.<table>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector.php#a0">aeVector</a>()</td><td><a class="el" href="classaeVector.php">aeVector</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector.php#a1">aeVector</a>(float nx, float ny=0)</td><td><a class="el" href="classaeVector.php">aeVector</a></td><td><code> [inline]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector.php#a2">aeVector</a>(const aeVector &amp;v)</td><td><a class="el" href="classaeVector.php">aeVector</a></td><td><code> [inline]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector.php#a12">Cross</a>(const aeVector &amp;v1, const aeVector &amp;v2)</td><td><a class="el" href="classaeVector.php">aeVector</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector.php#a13">Magnitude</a>() const</td><td><a class="el" href="classaeVector.php">aeVector</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector.php#a15">Normalize</a>() const</td><td><a class="el" href="classaeVector.php">aeVector</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector.php#l2">operator *</a>(const aeVector &amp;v1, const aeVector &amp;v2)</td><td><a class="el" href="classaeVector.php">aeVector</a></td><td><code> [friend]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector.php#l3">operator *</a>(const aeVector &amp;v1, float s)</td><td><a class="el" href="classaeVector.php">aeVector</a></td><td><code> [friend]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector.php#l4">operator *</a>(float s, const aeVector &amp;v1)</td><td><a class="el" href="classaeVector.php">aeVector</a></td><td><code> [friend]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector.php#l5">operator *</a>(int s, const aeVector &amp;v1)</td><td><a class="el" href="classaeVector.php">aeVector</a></td><td><code> [friend]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector.php#a6">operator *=</a>(float s)</td><td><a class="el" href="classaeVector.php">aeVector</a></td><td><code> [inline]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector.php#l9">operator!=</a>(const aeVector &amp;v1, const aeVector &amp;v2)</td><td><a class="el" href="classaeVector.php">aeVector</a></td><td><code> [friend]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector.php#l0">operator+</a>(const aeVector &amp;v1, const aeVector &amp;v2)</td><td><a class="el" href="classaeVector.php">aeVector</a></td><td><code> [friend]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector.php#a8">operator+</a>() const</td><td><a class="el" href="classaeVector.php">aeVector</a></td><td><code> [inline]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector.php#a4">operator+=</a>(const aeVector &amp;v1)</td><td><a class="el" href="classaeVector.php">aeVector</a></td><td><code> [inline]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector.php#l1">operator-</a>(const aeVector &amp;v1, const aeVector &amp;v2)</td><td><a class="el" href="classaeVector.php">aeVector</a></td><td><code> [friend]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector.php#a9">operator-</a>() const</td><td><a class="el" href="classaeVector.php">aeVector</a></td><td><code> [inline]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector.php#a5">operator-=</a>(const aeVector &amp;v1)</td><td><a class="el" href="classaeVector.php">aeVector</a></td><td><code> [inline]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector.php#l6">operator/</a>(const aeVector &amp;v1, float s)</td><td><a class="el" href="classaeVector.php">aeVector</a></td><td><code> [friend]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector.php#l7">operator/</a>(const aeVector &amp;v1, int s)</td><td><a class="el" href="classaeVector.php">aeVector</a></td><td><code> [friend]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector.php#a7">operator/=</a>(float s)</td><td><a class="el" href="classaeVector.php">aeVector</a></td><td><code> [inline]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector.php#l8">operator==</a>(const aeVector &amp;v1, const aeVector &amp;v2)</td><td><a class="el" href="classaeVector.php">aeVector</a></td><td><code> [friend]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector.php#a10">Set</a>(float nx, float ny)</td><td><a class="el" href="classaeVector.php">aeVector</a></td><td><code> [inline]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector.php#a11">Set</a>(const aeVector &amp;v)</td><td><a class="el" href="classaeVector.php">aeVector</a></td><td><code> [inline]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector.php#a14">Unit</a>() const</td><td><a class="el" href="classaeVector.php">aeVector</a></td><td><code> [inline]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector.php#m0">x</a></td><td><a class="el" href="classaeVector.php">aeVector</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeVector.php#m1">y</a></td><td><a class="el" href="classaeVector.php">aeVector</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td><b>~aeVector</b>() (defined in <a class="el" href="classaeVector.php">aeVector</a>)</td><td><a class="el" href="classaeVector.php">aeVector</a></td><td><code> [inline]</code></td></tr>
</table><hr><address style="align: right;"><small>Generated on Sun Mar 2 01:14:24 2003 for AE Engine by
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border=0 
width=110 height=53></a>1.3-rc2 </small></address>
</body>
</html>
