<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>aeUtil class Reference</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.3-rc2 -->
<center>
<a class="qindex" href="index.php">Main Page</a> &nbsp; <a class="qindex" href="modules.php">Modules</a> &nbsp; <a class="qindex" href="hierarchy.php">Class Hierarchy</a> &nbsp; <a class="qindex" href="classes.php">Alphabetical List</a> &nbsp; <a class="qindex" href="annotated.php">Compound List</a> &nbsp; <a class="qindex" href="files.php">File List</a> &nbsp; <a class="qindex" href="functions.php">Compound Members</a> &nbsp; </center>
<hr><h1>aeUtil Class Reference</h1>General static utility functions. 
<a href="#_details">More...</a>
<p>
<code>#include &lt;<a class="el" href="util_8h-source.php">util.h</a>&gt;</code>
<p>
<a href="classaeUtil-members.php">List of all members.</a><table border=0 cellpadding=0 cellspacing=0>
<tr><td></td></tr>
<tr><td colspan=2><br><h2>Static Public Methods</h2></td></tr>
<tr><td nowrap align=right valign=top>void&nbsp;</td><td valign=bottom><a class="el" href="classaeUtil.php#d0">Report</a> (const char *, const char *,...)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Report (print) text into the console.</em> <a href="#d0"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>bool&nbsp;</td><td valign=bottom><a class="el" href="classaeUtil.php#d1">aeUtil::InStr</a> (char *searchstr, char *str)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Checks if a string is included in another string.</em> <a href="#d1"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top><a class="el" href="classaeVector3.php">aeVector3</a>&nbsp;</td><td valign=bottom><a class="el" href="classaeUtil.php#d2">CalculateNormal</a> (const <a class="el" href="classaeVector3.php">aeVector3</a> &amp;v1, const <a class="el" href="classaeVector3.php">aeVector3</a> &amp;v2, const <a class="el" href="classaeVector3.php">aeVector3</a> &amp;v3)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Calculate normal for a triangle.</em> <a href="#d2"></a><em></em></font><br><br></td></tr>
</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
General static utility functions.
<p>

<p>
Definition at line <a class="el" href="util_8h-source.php#l00033">33</a> of file <a class="el" href="util_8h-source.php">util.h</a>.<hr><h2>Member Function Documentation</h2>
<a name="d1" doxytag="aeUtil::aeUtil::InStr"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> bool aeUtil::aeUtil::InStr </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">char *&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>searchstr</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>char *&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>str</em></td>
        </tr>
        <tr>
          <td></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [static]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Checks if a string is included in another string.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>searchstr</em>&nbsp;</td><td>String to search for. </td></tr>
    <tr><td valign=top><em>str</em>&nbsp;</td><td>String to search from.</td></tr>
  </table>
</dl>
<dl compact><dt><b>Returns:</b></dt><dd></dd></dl>
    </td>
  </tr>
</table>
<a name="d2" doxytag="aeUtil::CalculateNormal"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> <a class="el" href="classaeVector3.php">aeVector3</a> aeUtil::CalculateNormal </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">const <a class="el" href="classaeVector3.php">aeVector3</a> &amp;&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>v1</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>const <a class="el" href="classaeVector3.php">aeVector3</a> &amp;&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>v2</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>const <a class="el" href="classaeVector3.php">aeVector3</a> &amp;&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>v3</em></td>
        </tr>
        <tr>
          <td></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [static]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Calculate normal for a triangle.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>aeVector3</em>&nbsp;</td><td>&amp; First vertex of triangle. </td></tr>
    <tr><td valign=top><em>aeVector3</em>&nbsp;</td><td>&amp; Second vertex of triangle. </td></tr>
    <tr><td valign=top><em>aeVector3</em>&nbsp;</td><td>&amp; Third vertex of triangle.</td></tr>
  </table>
</dl>
<dl compact><dt><b>Returns:</b></dt><dd>Calculated normal for the triangle.</dd></dl>
    </td>
  </tr>
</table>
<a name="d0" doxytag="aeUtil::Report"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> void aeUtil::Report </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">const char *&nbsp;</td>
          <td class="mdname" nowrap>&nbsp;, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>const char *&nbsp;</td>
          <td class="mdname" nowrap>&nbsp;, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>...&nbsp;</td>
          <td class="mdname" nowrap>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [static]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Report (print) text into the console.
<p>
Formatting of message works just like in printf() etc. Use this for debugging or whatever printing you need to do (to the console).
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>const</em>&nbsp;</td><td>char * Where from the message comes (e.g. "ae.engine.Render"). </td></tr>
    <tr><td valign=top><em>const</em>&nbsp;</td><td>char * The message to print. </td></tr>
    <tr><td valign=top><em>...</em>&nbsp;</td><td>Any modifiers</td></tr>
  </table>
</dl>
    </td>
  </tr>
</table>
<hr>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="util_8h-source.php">util.h</a></ul>
<hr><address style="align: right;"><small>Generated on Sun Mar 2 01:14:23 2003 for AE Engine by
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border=0 
width=110 height=53></a>1.3-rc2 </small></address>
</body>
</html>
