<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>aeBlockDescriptor class Reference</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.3-rc2 -->
<center>
<a class="qindex" href="index.php">Main Page</a> &nbsp; <a class="qindex" href="modules.php">Modules</a> &nbsp; <a class="qindex" href="hierarchy.php">Class Hierarchy</a> &nbsp; <a class="qindex" href="classes.php">Alphabetical List</a> &nbsp; <a class="qindex" href="annotated.php">Compound List</a> &nbsp; <a class="qindex" href="files.php">File List</a> &nbsp; <a class="qindex" href="functions.php">Compound Members</a> &nbsp; </center>
<hr><h1>aeBlockDescriptor Class Reference</h1>This class describes allocated memory-chunks. 
<a href="#_details">More...</a>
<p>
<code>#include &lt;<a class="el" href="blockdescriptor_8h-source.php">blockdescriptor.h</a>&gt;</code>
<p>
<a href="classaeBlockDescriptor-members.php">List of all members.</a><table border=0 cellpadding=0 cellspacing=0>
<tr><td></td></tr>
<tr><td colspan=2><br><h2>Public Methods</h2></td></tr>
<tr><td nowrap align=right valign=top><a name="a0" doxytag="aeBlockDescriptor::aeBlockDescriptor"></a>
&nbsp;</td><td valign=bottom><b>aeBlockDescriptor</b> (void *addr, size_t size, const char *filename, int linenumber)</td></tr>
<tr><td colspan=2><br><h2>Public Attributes</h2></td></tr>
<tr><td nowrap align=right valign=top><a name="m0" doxytag="aeBlockDescriptor::m_addr"></a>
void *&nbsp;</td><td valign=bottom><b>m_addr</b></td></tr>
<tr><td nowrap align=right valign=top><a name="m1" doxytag="aeBlockDescriptor::m_size"></a>
size_t&nbsp;</td><td valign=bottom><b>m_size</b></td></tr>
<tr><td nowrap align=right valign=top><a name="m2" doxytag="aeBlockDescriptor::m_pfilename"></a>
char *&nbsp;</td><td valign=bottom><b>m_pfilename</b></td></tr>
<tr><td nowrap align=right valign=top><a name="m3" doxytag="aeBlockDescriptor::m_linenumber"></a>
int&nbsp;</td><td valign=bottom><b>m_linenumber</b></td></tr>
</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
This class describes allocated memory-chunks.
<p>
On its own destruction, it does *not* free the memory-block it describes. 
<p>

<p>
Definition at line <a class="el" href="blockdescriptor_8h-source.php#l00036">36</a> of file <a class="el" href="blockdescriptor_8h-source.php">blockdescriptor.h</a>.<hr>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="blockdescriptor_8h-source.php">blockdescriptor.h</a></ul>
<hr><address style="align: right;"><small>Generated on Sun Mar 2 01:14:23 2003 for AE Engine by
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border=0 
width=110 height=53></a>1.3-rc2 </small></address>
</body>
</html>
