<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>Member List</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.3-rc2 -->
<center>
<a class="qindex" href="index.php">Main Page</a> &nbsp; <a class="qindex" href="modules.php">Modules</a> &nbsp; <a class="qindex" href="hierarchy.php">Class Hierarchy</a> &nbsp; <a class="qindex" href="classes.php">Alphabetical List</a> &nbsp; <a class="qindex" href="annotated.php">Compound List</a> &nbsp; <a class="qindex" href="files.php">File List</a> &nbsp; <a class="qindex" href="functions.php">Compound Members</a> &nbsp; </center>
<hr><h1>aeTerrMan Member List</h1>This is the complete list of members for <a class="el" href="classaeTerrMan.php">aeTerrMan</a>, including all inherited members.<table>
  <tr bgcolor="#f0f0f0"><td><b>aeTerrMan</b>(aeRegistry *aeReg) (defined in <a class="el" href="classaeTerrMan.php">aeTerrMan</a>)</td><td><a class="el" href="classaeTerrMan.php">aeTerrMan</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeBase.php#b1">ASSERT</a>(bool isok, char *desc,...)</td><td><a class="el" href="classaeBase.php">aeBase</a></td><td><code> [protected, virtual]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeTerrMan.php#a2">GetObject</a>() const</td><td><a class="el" href="classaeTerrMan.php">aeTerrMan</a></td><td><code> [inline, virtual]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaePlugin.php#a1">GetPluginID</a>() const</td><td><a class="el" href="classaePlugin.php">aePlugin</a></td><td><code> [inline]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeTerrMan.php#a6">LoadHeightMap</a>(char *filename)</td><td><a class="el" href="classaeTerrMan.php">aeTerrMan</a></td><td><code> [virtual]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><b>LOGLEVEL</b> (defined in <a class="el" href="classaeBase.php">aeBase</a>)</td><td><a class="el" href="classaeBase.php">aeBase</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaePlugin.php#m0">myID</a></td><td><a class="el" href="classaePlugin.php">aePlugin</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeBase.php#b0">Report</a>(int loglevel, const char *msg,...)</td><td><a class="el" href="classaeBase.php">aeBase</a></td><td><code> [protected, virtual]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeTerrMan.php#a5">SetMaterial</a>(aeMaterial *)</td><td><a class="el" href="classaeTerrMan.php">aeTerrMan</a></td><td><code> [virtual]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeTerrMan.php#a3">SetOrigin</a>(float x, float y, float z)</td><td><a class="el" href="classaeTerrMan.php">aeTerrMan</a></td><td><code> [virtual]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><a class="el" href="classaeTerrMan.php#a4">SetOrigin</a>(aeVector3)</td><td><a class="el" href="classaeTerrMan.php">aeTerrMan</a></td><td><code> [virtual]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><b>~aeBase</b>() (defined in <a class="el" href="classaeBase.php">aeBase</a>)</td><td><a class="el" href="classaeBase.php">aeBase</a></td><td><code> [virtual]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><b>~aePlugin</b>() (defined in <a class="el" href="classaePlugin.php">aePlugin</a>)</td><td><a class="el" href="classaePlugin.php">aePlugin</a></td><td><code> [inline, virtual]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><b>~aeTerrMan</b>() (defined in <a class="el" href="classaeTerrMan.php">aeTerrMan</a>)</td><td><a class="el" href="classaeTerrMan.php">aeTerrMan</a></td><td></td></tr>
</table><hr><address style="align: right;"><small>Generated on Sun Mar 2 01:14:23 2003 for AE Engine by
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border=0 
width=110 height=53></a>1.3-rc2 </small></address>
</body>
</html>
