<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>aeVector class Reference</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.3-rc2 -->
<center>
<a class="qindex" href="index.php">Main Page</a> &nbsp; <a class="qindex" href="modules.php">Modules</a> &nbsp; <a class="qindex" href="hierarchy.php">Class Hierarchy</a> &nbsp; <a class="qindex" href="classes.php">Alphabetical List</a> &nbsp; <a class="qindex" href="annotated.php">Compound List</a> &nbsp; <a class="qindex" href="files.php">File List</a> &nbsp; <a class="qindex" href="functions.php">Compound Members</a> &nbsp; </center>
<hr><h1>aeVector Class Reference</h1>A 2D vector. 
<a href="#_details">More...</a>
<p>
<code>#include &lt;<a class="el" href="vector_8h-source.php">vector.h</a>&gt;</code>
<p>
<a href="classaeVector-members.php">List of all members.</a><table border=0 cellpadding=0 cellspacing=0>
<tr><td></td></tr>
<tr><td colspan=2><br><h2>Public Methods</h2></td></tr>
<tr><td nowrap align=right valign=top>&nbsp;</td><td valign=bottom><a class="el" href="classaeVector.php#a0">aeVector</a> ()</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Create a new vector and initialize it to 0, 0.</em> <a href="#a0"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>&nbsp;</td><td valign=bottom><a class="el" href="classaeVector.php#a1">aeVector</a> (float nx, float ny=0)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Create a new vector and initialize it to x, y.</em> <a href="#a1"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>&nbsp;</td><td valign=bottom><a class="el" href="classaeVector.php#a2">aeVector</a> (const aeVector &amp;v)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Copy constructor.</em> <a href="#a2"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>aeVector &amp;&nbsp;</td><td valign=bottom><a class="el" href="classaeVector.php#a4">operator+=</a> (const aeVector &amp;v1)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Add another vector to this vector.</em> <a href="#a4"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>aeVector &amp;&nbsp;</td><td valign=bottom><a class="el" href="classaeVector.php#a5">operator-=</a> (const aeVector &amp;v1)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Subtract another vector from this vector.</em> <a href="#a5"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>aeVector &amp;&nbsp;</td><td valign=bottom><a class="el" href="classaeVector.php#a6">operator *=</a> (float s)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Multiply by scalar float.</em> <a href="#a6"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>aeVector &amp;&nbsp;</td><td valign=bottom><a class="el" href="classaeVector.php#a7">operator/=</a> (float s)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Divide by scalar float.</em> <a href="#a7"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>aeVector&nbsp;</td><td valign=bottom><a class="el" href="classaeVector.php#a8">operator+</a> () const</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Unary +.</em> <a href="#a8"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>aeVector&nbsp;</td><td valign=bottom><a class="el" href="classaeVector.php#a9">operator-</a> () const</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Unary - (negate this vector).</em> <a href="#a9"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>void&nbsp;</td><td valign=bottom><a class="el" href="classaeVector.php#a10">Set</a> (float nx, float ny)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Set this vector to given x, y.</em> <a href="#a10"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>void&nbsp;</td><td valign=bottom><a class="el" href="classaeVector.php#a11">Set</a> (const aeVector &amp;v)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Set this vector to another vector.</em> <a href="#a11"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>aeVector&nbsp;</td><td valign=bottom><a class="el" href="classaeVector.php#a12">Cross</a> (const aeVector &amp;v1, const aeVector &amp;v2)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Get the cross product of two vectors and store the result in this vector.</em> <a href="#a12"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>float&nbsp;</td><td valign=bottom><a class="el" href="classaeVector.php#a13">Magnitude</a> () const</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Get the magnitude (lenght) of this vector.</em> <a href="#a13"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>aeVector&nbsp;</td><td valign=bottom><a class="el" href="classaeVector.php#a14">Unit</a> () const</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Get the unit vector of this vector.</em> <a href="#a14"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>aeVector&nbsp;</td><td valign=bottom><a class="el" href="classaeVector.php#a15">Normalize</a> () const</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Normalize this vector.</em> <a href="#a15"></a><em></em></font><br><br></td></tr>
<tr><td colspan=2><br><h2>Public Attributes</h2></td></tr>
<tr><td nowrap align=right valign=top><a name="m0" doxytag="aeVector::x"></a>
float&nbsp;</td><td valign=bottom><a class="el" href="classaeVector.php#m0">x</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>The X component of the vector.</em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top><a name="m1" doxytag="aeVector::y"></a>
float&nbsp;</td><td valign=bottom><a class="el" href="classaeVector.php#m1">y</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>The Y component of the vector.</em></font><br><br></td></tr>
<tr><td colspan=2><br><h2>Friends</h2></td></tr>
<tr><td nowrap align=right valign=top>aeVector&nbsp;</td><td valign=bottom><a class="el" href="classaeVector.php#l0">operator+</a> (const aeVector &amp;v1, const aeVector &amp;v2)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Add two vectors.</em> <a href="#l0"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>aeVector&nbsp;</td><td valign=bottom><a class="el" href="classaeVector.php#l1">operator-</a> (const aeVector &amp;v1, const aeVector &amp;v2)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Subtract two vectors.</em> <a href="#l1"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>float&nbsp;</td><td valign=bottom><a class="el" href="classaeVector.php#l2">operator *</a> (const aeVector &amp;v1, const aeVector &amp;v2)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Dot product of two vectors.</em> <a href="#l2"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>aeVector&nbsp;</td><td valign=bottom><a class="el" href="classaeVector.php#l3">operator *</a> (const aeVector &amp;v1, float s)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Multiply by scalar float.</em> <a href="#l3"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>aeVector&nbsp;</td><td valign=bottom><a class="el" href="classaeVector.php#l4">operator *</a> (float s, const aeVector &amp;v1)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Multiply by scalar float.</em> <a href="#l4"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>aeVector&nbsp;</td><td valign=bottom><a class="el" href="classaeVector.php#l5">operator *</a> (int s, const aeVector &amp;v1)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Multiply by scalar integer.</em> <a href="#l5"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>aeVector&nbsp;</td><td valign=bottom><a class="el" href="classaeVector.php#l6">operator/</a> (const aeVector &amp;v1, float s)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Divide by scalar float.</em> <a href="#l6"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>aeVector&nbsp;</td><td valign=bottom><a class="el" href="classaeVector.php#l7">operator/</a> (const aeVector &amp;v1, int s)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Divide by scalar integer.</em> <a href="#l7"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>bool&nbsp;</td><td valign=bottom><a class="el" href="classaeVector.php#l8">operator==</a> (const aeVector &amp;v1, const aeVector &amp;v2)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Check if two vectors are equal.</em> <a href="#l8"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>bool&nbsp;</td><td valign=bottom><a class="el" href="classaeVector.php#l9">operator!=</a> (const aeVector &amp;v1, const aeVector &amp;v2)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Check if two vectors are not equal.</em> <a href="#l9"></a><em></em></font><br><br></td></tr>
</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
A 2D vector.
<p>

<p>
Definition at line <a class="el" href="vector_8h-source.php#l00033">33</a> of file <a class="el" href="vector_8h-source.php">vector.h</a>.<hr><h2>Constructor &amp; Destructor Documentation</h2>
<a name="a0" doxytag="aeVector::aeVector"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> aeVector::aeVector </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Create a new vector and initialize it to 0, 0.
<p>

<p>
Referenced by <a class="el" href="vector_8h-source.php#l00253">operator-()</a>.    </td>
  </tr>
</table>
<a name="a1" doxytag="aeVector::aeVector"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> aeVector::aeVector </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">float&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>nx</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>float&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>ny</em> = 0</td>
        </tr>
        <tr>
          <td></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [inline]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Create a new vector and initialize it to x, y.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>x</em>&nbsp;</td><td>The vector's X component. </td></tr>
    <tr><td valign=top><em>y</em>&nbsp;</td><td>The vector's Y component.</td></tr>
  </table>
</dl>

<p>
Definition at line <a class="el" href="vector_8h-source.php#l00049">49</a> of file <a class="el" href="vector_8h-source.php">vector.h</a>.
<p>
References <a class="el" href="vector_8h-source.php#l00061">x</a>, and <a class="el" href="vector_8h-source.php#l00063">y</a>.    </td>
  </tr>
</table>
<a name="a2" doxytag="aeVector::aeVector"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> aeVector::aeVector </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">const aeVector &amp;&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp; <em>v</em>          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap><code> [inline]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Copy constructor.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>v</em>&nbsp;</td><td>Vector to copy to this vector.</td></tr>
  </table>
</dl>

<p>
Definition at line <a class="el" href="vector_8h-source.php#l00056">56</a> of file <a class="el" href="vector_8h-source.php">vector.h</a>.
<p>
References <a class="el" href="vector_8h-source.php#l00061">x</a>, and <a class="el" href="vector_8h-source.php#l00063">y</a>.    </td>
  </tr>
</table>
<hr><h2>Member Function Documentation</h2>
<a name="a12" doxytag="aeVector::Cross"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> aeVector aeVector::Cross </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">const aeVector &amp;&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>v1</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>const aeVector &amp;&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>v2</em></td>
        </tr>
        <tr>
          <td></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Get the cross product of two vectors and store the result in this vector.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>v1</em>&nbsp;</td><td>Vector1. </td></tr>
    <tr><td valign=top><em>v2</em>&nbsp;</td><td>Vector2.</td></tr>
  </table>
</dl>
    </td>
  </tr>
</table>
<a name="a13" doxytag="aeVector::Magnitude"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> float aeVector::Magnitude </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap> const</td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Get the magnitude (lenght) of this vector.
<p>
<dl compact><dt><b>Returns:</b></dt><dd>The vector's magnitude.</dd></dl>
    </td>
  </tr>
</table>
<a name="a15" doxytag="aeVector::Normalize"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> aeVector aeVector::Normalize </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap> const</td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Normalize this vector.
<p>
<dl compact><dt><b>Returns:</b></dt><dd>The normalized vector.</dd></dl>

<p>
Referenced by <a class="el" href="vector_8h-source.php#l00299">Unit()</a>.    </td>
  </tr>
</table>
<a name="a6" doxytag="aeVector::operator *="></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> aeVector&amp; aeVector::operator *= </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">float&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp; <em>s</em>          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap><code> [inline]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Multiply by scalar float.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>s</em>&nbsp;</td><td>Scalar float</td></tr>
  </table>
</dl>
<dl compact><dt><b>Returns:</b></dt><dd>This vector * scalar float.</dd></dl>

<p>
Definition at line <a class="el" href="vector_8h-source.php#l00219">219</a> of file <a class="el" href="vector_8h-source.php">vector.h</a>.    </td>
  </tr>
</table>
<a name="a8" doxytag="aeVector::operator+"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> aeVector aeVector::operator+ </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap> const<code> [inline]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Unary +.
<p>
<dl compact><dt><b>Returns:</b></dt><dd>This vector.</dd></dl>

<p>
Definition at line <a class="el" href="vector_8h-source.php#l00245">245</a> of file <a class="el" href="vector_8h-source.php">vector.h</a>.    </td>
  </tr>
</table>
<a name="a4" doxytag="aeVector::operator+="></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> aeVector&amp; aeVector::operator+= </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">const aeVector &amp;&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp; <em>v1</em>          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap><code> [inline]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Add another vector to this vector.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>v1</em>&nbsp;</td><td>Vector to add.</td></tr>
  </table>
</dl>
<dl compact><dt><b>Returns:</b></dt><dd>This vector + another vector.</dd></dl>

<p>
Definition at line <a class="el" href="vector_8h-source.php#l00193">193</a> of file <a class="el" href="vector_8h-source.php">vector.h</a>.    </td>
  </tr>
</table>
<a name="a9" doxytag="aeVector::operator-"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> aeVector aeVector::operator- </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap> const<code> [inline]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Unary - (negate this vector).
<p>
<dl compact><dt><b>Returns:</b></dt><dd>This vector negated.</dd></dl>

<p>
Definition at line <a class="el" href="vector_8h-source.php#l00253">253</a> of file <a class="el" href="vector_8h-source.php">vector.h</a>.
<p>
References <a class="el" href="classaeVector.php#a0">aeVector()</a>.    </td>
  </tr>
</table>
<a name="a5" doxytag="aeVector::operator-="></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> aeVector&amp; aeVector::operator-= </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">const aeVector &amp;&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp; <em>v1</em>          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap><code> [inline]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Subtract another vector from this vector.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>v1</em>&nbsp;</td><td>Vector to subtract.</td></tr>
  </table>
</dl>
<dl compact><dt><b>Returns:</b></dt><dd>This vector / another vector.</dd></dl>

<p>
Definition at line <a class="el" href="vector_8h-source.php#l00206">206</a> of file <a class="el" href="vector_8h-source.php">vector.h</a>.    </td>
  </tr>
</table>
<a name="a7" doxytag="aeVector::operator/="></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> aeVector&amp; aeVector::operator/= </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">float&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp; <em>s</em>          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap><code> [inline]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Divide by scalar float.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>s</em>&nbsp;</td><td>Scalar float.</td></tr>
  </table>
</dl>
<dl compact><dt><b>Returns:</b></dt><dd>This vector / scalar float.</dd></dl>

<p>
Definition at line <a class="el" href="vector_8h-source.php#l00232">232</a> of file <a class="el" href="vector_8h-source.php">vector.h</a>.    </td>
  </tr>
</table>
<a name="a11" doxytag="aeVector::Set"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> void aeVector::Set </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">const aeVector &amp;&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp; <em>v</em>          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap><code> [inline]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Set this vector to another vector.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>v</em>&nbsp;</td><td>Vector to set this vector to.</td></tr>
  </table>
</dl>

<p>
Definition at line <a class="el" href="vector_8h-source.php#l00271">271</a> of file <a class="el" href="vector_8h-source.php">vector.h</a>.    </td>
  </tr>
</table>
<a name="a10" doxytag="aeVector::Set"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> void aeVector::Set </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">float&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>nx</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>float&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>ny</em></td>
        </tr>
        <tr>
          <td></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [inline]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Set this vector to given x, y.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>nx</em>&nbsp;</td><td>The value to set the x component of this vector to. </td></tr>
    <tr><td valign=top><em>ny</em>&nbsp;</td><td>The value to set the y component of this vector to.</td></tr>
  </table>
</dl>

<p>
Definition at line <a class="el" href="vector_8h-source.php#l00261">261</a> of file <a class="el" href="vector_8h-source.php">vector.h</a>.    </td>
  </tr>
</table>
<a name="a14" doxytag="aeVector::Unit"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> aeVector aeVector::Unit </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>&nbsp;          </td>
          <td class="md" valign="top">)&nbsp;</td>
          <td class="md" nowrap> const<code> [inline]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Get the unit vector of this vector.
<p>
This is essentialy the same as <a class="el" href="classaeVector.php#a15">Normalize()</a>.
<p>
<dl compact><dt><b>See also:</b></dt><dd><a class="el" href="classaeVector.php#a15">aeVector::Normalize()</a></dd></dl>
<dl compact><dt><b>Returns:</b></dt><dd></dd></dl>

<p>
Definition at line <a class="el" href="vector_8h-source.php#l00299">299</a> of file <a class="el" href="vector_8h-source.php">vector.h</a>.
<p>
References <a class="el" href="classaeVector.php#a15">Normalize()</a>.    </td>
  </tr>
</table>
<hr><h2>Friends And Related Function Documentation</h2>
<a name="l5" doxytag="aeVector::operator *"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> aeVector operator * </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">int&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>s</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>const aeVector &amp;&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>v1</em></td>
        </tr>
        <tr>
          <td></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [friend]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Multiply by scalar integer.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>s</em>&nbsp;</td><td>Scalar integer. </td></tr>
    <tr><td valign=top><em>v1</em>&nbsp;</td><td>Vector.</td></tr>
  </table>
</dl>
<dl compact><dt><b>Returns:</b></dt><dd>Scalar integer * vector</dd></dl>

<p>
Definition at line <a class="el" href="vector_8h-source.php#l00133">133</a> of file <a class="el" href="vector_8h-source.php">vector.h</a>.    </td>
  </tr>
</table>
<a name="l4" doxytag="aeVector::operator *"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> aeVector operator * </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">float&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>s</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>const aeVector &amp;&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>v1</em></td>
        </tr>
        <tr>
          <td></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [friend]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Multiply by scalar float.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>s</em>&nbsp;</td><td>Scalar float. </td></tr>
    <tr><td valign=top><em>v1</em>&nbsp;</td><td>Vector.</td></tr>
  </table>
</dl>
<dl compact><dt><b>Returns:</b></dt><dd>Scalar float * vector.</dd></dl>

<p>
Definition at line <a class="el" href="vector_8h-source.php#l00121">121</a> of file <a class="el" href="vector_8h-source.php">vector.h</a>.    </td>
  </tr>
</table>
<a name="l3" doxytag="aeVector::operator *"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> aeVector operator * </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">const aeVector &amp;&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>v1</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>float&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>s</em></td>
        </tr>
        <tr>
          <td></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [friend]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Multiply by scalar float.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>v1</em>&nbsp;</td><td>Vector. </td></tr>
    <tr><td valign=top><em>s</em>&nbsp;</td><td>Scalar float.</td></tr>
  </table>
</dl>
<dl compact><dt><b>Returns:</b></dt><dd>Vector * scalar float.</dd></dl>

<p>
Definition at line <a class="el" href="vector_8h-source.php#l00109">109</a> of file <a class="el" href="vector_8h-source.php">vector.h</a>.    </td>
  </tr>
</table>
<a name="l2" doxytag="aeVector::operator *"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> float operator * </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">const aeVector &amp;&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>v1</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>const aeVector &amp;&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>v2</em></td>
        </tr>
        <tr>
          <td></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [friend]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Dot product of two vectors.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>v1</em>&nbsp;</td><td>Vector1. </td></tr>
    <tr><td valign=top><em>v2</em>&nbsp;</td><td>Vector2.</td></tr>
  </table>
</dl>
<dl compact><dt><b>Returns:</b></dt><dd>Vector1 . Vector2.</dd></dl>

<p>
Definition at line <a class="el" href="vector_8h-source.php#l00097">97</a> of file <a class="el" href="vector_8h-source.php">vector.h</a>.    </td>
  </tr>
</table>
<a name="l9" doxytag="aeVector::operator!="></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> bool operator!= </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">const aeVector &amp;&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>v1</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>const aeVector &amp;&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>v2</em></td>
        </tr>
        <tr>
          <td></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [friend]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Check if two vectors are not equal.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>v1</em>&nbsp;</td><td>Vector1 </td></tr>
    <tr><td valign=top><em>v2</em>&nbsp;</td><td>Vector2</td></tr>
  </table>
</dl>
<dl compact><dt><b>Returns:</b></dt><dd>True if Vector1 != Vector2, false if not.</dd></dl>

<p>
Definition at line <a class="el" href="vector_8h-source.php#l00182">182</a> of file <a class="el" href="vector_8h-source.php">vector.h</a>.    </td>
  </tr>
</table>
<a name="l0" doxytag="aeVector::operator+"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> aeVector operator+ </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">const aeVector &amp;&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>v1</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>const aeVector &amp;&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>v2</em></td>
        </tr>
        <tr>
          <td></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [friend]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Add two vectors.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>v1</em>&nbsp;</td><td>Vector1. </td></tr>
    <tr><td valign=top><em>v2</em>&nbsp;</td><td>Vector2.</td></tr>
  </table>
</dl>
<dl compact><dt><b>Returns:</b></dt><dd>Vector1 + Vector2.</dd></dl>

<p>
Definition at line <a class="el" href="vector_8h-source.php#l00073">73</a> of file <a class="el" href="vector_8h-source.php">vector.h</a>.    </td>
  </tr>
</table>
<a name="l1" doxytag="aeVector::operator-"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> aeVector operator- </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">const aeVector &amp;&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>v1</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>const aeVector &amp;&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>v2</em></td>
        </tr>
        <tr>
          <td></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [friend]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Subtract two vectors.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>v1</em>&nbsp;</td><td>Vector1. </td></tr>
    <tr><td valign=top><em>v2</em>&nbsp;</td><td>Vector2.</td></tr>
  </table>
</dl>
<dl compact><dt><b>Returns:</b></dt><dd>Vector1 - Vector2.</dd></dl>

<p>
Definition at line <a class="el" href="vector_8h-source.php#l00085">85</a> of file <a class="el" href="vector_8h-source.php">vector.h</a>.    </td>
  </tr>
</table>
<a name="l7" doxytag="aeVector::operator/"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> aeVector operator/ </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">const aeVector &amp;&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>v1</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>int&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>s</em></td>
        </tr>
        <tr>
          <td></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [friend]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Divide by scalar integer.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>v1</em>&nbsp;</td><td>Vector. </td></tr>
    <tr><td valign=top><em>s</em>&nbsp;</td><td>Scalar integer.</td></tr>
  </table>
</dl>
<dl compact><dt><b>Returns:</b></dt><dd>Vector / scalar integer.</dd></dl>

<p>
Definition at line <a class="el" href="vector_8h-source.php#l00158">158</a> of file <a class="el" href="vector_8h-source.php">vector.h</a>.    </td>
  </tr>
</table>
<a name="l6" doxytag="aeVector::operator/"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> aeVector operator/ </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">const aeVector &amp;&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>v1</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>float&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>s</em></td>
        </tr>
        <tr>
          <td></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [friend]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Divide by scalar float.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>v1</em>&nbsp;</td><td>Vector. </td></tr>
    <tr><td valign=top><em>s</em>&nbsp;</td><td>Scalar float.</td></tr>
  </table>
</dl>
<dl compact><dt><b>Returns:</b></dt><dd>Vector / scalar float.</dd></dl>

<p>
Definition at line <a class="el" href="vector_8h-source.php#l00145">145</a> of file <a class="el" href="vector_8h-source.php">vector.h</a>.    </td>
  </tr>
</table>
<a name="l8" doxytag="aeVector::operator=="></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> bool operator== </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">const aeVector &amp;&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>v1</em>, </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="md" nowrap>const aeVector &amp;&nbsp;</td>
          <td class="mdname" nowrap>&nbsp; <em>v2</em></td>
        </tr>
        <tr>
          <td></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [friend]</code></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Check if two vectors are equal.
<p>
<dl compact><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign=top><em>v1</em>&nbsp;</td><td>Vector1 </td></tr>
    <tr><td valign=top><em>v2</em>&nbsp;</td><td>Vector2</td></tr>
  </table>
</dl>
<dl compact><dt><b>Returns:</b></dt><dd>True if Vector1 == Vector2, false if not.</dd></dl>

<p>
Definition at line <a class="el" href="vector_8h-source.php#l00170">170</a> of file <a class="el" href="vector_8h-source.php">vector.h</a>.    </td>
  </tr>
</table>
<hr>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="vector_8h-source.php">vector.h</a></ul>
<hr><address style="align: right;"><small>Generated on Sun Mar 2 01:14:23 2003 for AE Engine by
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border=0 
width=110 height=53></a>1.3-rc2 </small></address>
</body>
</html>
