<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>config.h Source File</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.3-rc2 -->
<center>
<a class="qindex" href="index.php">Main Page</a> &nbsp; <a class="qindex" href="modules.php">Modules</a> &nbsp; <a class="qindex" href="hierarchy.php">Class Hierarchy</a> &nbsp; <a class="qindex" href="classes.php">Alphabetical List</a> &nbsp; <a class="qindex" href="annotated.php">Compound List</a> &nbsp; <a class="qindex" href="files.php">File List</a> &nbsp; <a class="qindex" href="functions.php">Compound Members</a> &nbsp; </center>
<hr><h1>config.h</h1><div class="fragment"><pre>00001 <span class="comment">/* include/config.h.  Generated by configure.  */</span>
00002 <span class="comment">/* include/config.h.in.  Generated from configure.ac by autoheader.  */</span>
00003 
00004 <span class="comment">/* Define to 1 to set debug mode on */</span>
00005 <span class="preprocessor">#define DEBUG 1</span>
00006 <span class="preprocessor"></span>
00007 <span class="comment">/* Define to 1 if you have the &lt;dlfcn.h&gt; header file. */</span>
00008 <span class="preprocessor">#define HAVE_DLFCN_H 1</span>
00009 <span class="preprocessor"></span>
00010 <span class="comment">/* Define to 1 if you have the &lt;inttypes.h&gt; header file. */</span>
00011 <span class="preprocessor">#define HAVE_INTTYPES_H 1</span>
00012 <span class="preprocessor"></span>
00013 <span class="comment">/* Define to 1 if you have the `dl' library (-ldl). */</span>
00014 <span class="preprocessor">#define HAVE_LIBDL 1</span>
00015 <span class="preprocessor"></span>
00016 <span class="comment">/* Define to 1 if you have the &lt;memory.h&gt; header file. */</span>
00017 <span class="preprocessor">#define HAVE_MEMORY_H 1</span>
00018 <span class="preprocessor"></span>
00019 <span class="comment">/* Define to 1 if you have the &lt;stdint.h&gt; header file. */</span>
00020 <span class="preprocessor">#define HAVE_STDINT_H 1</span>
00021 <span class="preprocessor"></span>
00022 <span class="comment">/* Define to 1 if you have the &lt;stdlib.h&gt; header file. */</span>
00023 <span class="preprocessor">#define HAVE_STDLIB_H 1</span>
00024 <span class="preprocessor"></span>
00025 <span class="comment">/* Define to 1 if you have the &lt;strings.h&gt; header file. */</span>
00026 <span class="preprocessor">#define HAVE_STRINGS_H 1</span>
00027 <span class="preprocessor"></span>
00028 <span class="comment">/* Define to 1 if you have the &lt;string.h&gt; header file. */</span>
00029 <span class="preprocessor">#define HAVE_STRING_H 1</span>
00030 <span class="preprocessor"></span>
00031 <span class="comment">/* Define to 1 if you have the &lt;sys/stat.h&gt; header file. */</span>
00032 <span class="preprocessor">#define HAVE_SYS_STAT_H 1</span>
00033 <span class="preprocessor"></span>
00034 <span class="comment">/* Define to 1 if you have the &lt;sys/types.h&gt; header file. */</span>
00035 <span class="preprocessor">#define HAVE_SYS_TYPES_H 1</span>
00036 <span class="preprocessor"></span>
00037 <span class="comment">/* Define to 1 if you have the &lt;unistd.h&gt; header file. */</span>
00038 <span class="preprocessor">#define HAVE_UNISTD_H 1</span>
00039 <span class="preprocessor"></span>
00040 <span class="comment">/* Define to the address where bug reports for this package should be sent. */</span>
00041 <span class="preprocessor">#define PACKAGE_BUGREPORT "ae-bugs@madqon.org"</span>
00042 <span class="preprocessor"></span>
00043 <span class="comment">/* Define to the full name of this package. */</span>
00044 <span class="preprocessor">#define PACKAGE_NAME "AE Engine"</span>
00045 <span class="preprocessor"></span>
00046 <span class="comment">/* Define to the full name and version of this package. */</span>
00047 <span class="preprocessor">#define PACKAGE_STRING "AE Engine 0.1"</span>
00048 <span class="preprocessor"></span>
00049 <span class="comment">/* Define to the one symbol short name of this package. */</span>
00050 <span class="preprocessor">#define PACKAGE_TARNAME "ae"</span>
00051 <span class="preprocessor"></span>
00052 <span class="comment">/* Define to the version of this package. */</span>
00053 <span class="preprocessor">#define PACKAGE_VERSION "0.1"</span>
00054 <span class="preprocessor"></span>
00055 <span class="comment">/* Define to 1 if you have the ANSI C header files. */</span>
00056 <span class="preprocessor">#define STDC_HEADERS 1</span>
00057 <span class="preprocessor"></span>
00058 <span class="comment">/* Define to 1 if the X Window System is missing or not being used. */</span>
00059 <span class="comment">/* #undef X_DISPLAY_MISSING */</span>
00060 
00061 <span class="comment">/* Define to `unsigned' if &lt;sys/types.h&gt; does not define. */</span>
00062 <span class="comment">/* #undef size_t */</span>
</pre></div><hr><address style="align: right;"><small>Generated on Fri Feb 28 17:25:51 2003 for AE Engine by
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border=0 
width=110 height=53></a>1.3-rc2 </small></address>
</body>
</html>
