<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>engine.h Source File</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.3-rc2 -->
<center>
<a class="qindex" href="index.php">Main Page</a> &nbsp; <a class="qindex" href="modules.php">Modules</a> &nbsp; <a class="qindex" href="hierarchy.php">Class Hierarchy</a> &nbsp; <a class="qindex" href="classes.php">Alphabetical List</a> &nbsp; <a class="qindex" href="annotated.php">Compound List</a> &nbsp; <a class="qindex" href="files.php">File List</a> &nbsp; <a class="qindex" href="functions.php">Compound Members</a> &nbsp; </center>
<hr><h1>engine.h</h1><div class="fragment"><pre>00001 <span class="comment">/*</span>
00002 <span class="comment"> *  AE Engine</span>
00003 <span class="comment"> *</span>
00004 <span class="comment"> *  Copyright (C) 2003 Riku "Rakkis" Nurminen</span>
00005 <span class="comment"> *</span>
00006 <span class="comment"> *  This program is free software; you can redistribute it and/or modify</span>
00007 <span class="comment"> *  it under the terms of the GNU General Public License as published by</span>
00008 <span class="comment"> *  the Free Software Foundation; either version 2 of the License, or</span>
00009 <span class="comment"> *  (at your option) any later version.</span>
00010 <span class="comment"> *</span>
00011 <span class="comment"> *  This program is distributed in the hope that it will be useful,</span>
00012 <span class="comment"> *  but WITHOUT ANY WARRANTY; without even the implied warranty of</span>
00013 <span class="comment"> *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the</span>
00014 <span class="comment"> *  GNU General Public License for more details.</span>
00015 <span class="comment"> *</span>
00016 <span class="comment"> *  You should have received a copy of the GNU General Public License</span>
00017 <span class="comment"> *  along with this program; if not, write to the Free Software</span>
00018 <span class="comment"> *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA</span>
00019 <span class="comment"> *</span>
00020 <span class="comment"> */</span>
00021 
00022 <span class="preprocessor">#ifndef __AELIB_AEENGINE_ENGINE_H__</span>
00023 <span class="preprocessor"></span><span class="preprocessor">#define __AELIB_AEENGINE_ENGINE_H__</span>
00024 <span class="preprocessor"></span>
00025 <span class="preprocessor">#include &lt;aedefs.h&gt;</span>
00026 <span class="preprocessor">#include &lt;aeengine/camera.h&gt;</span>
00027 <span class="preprocessor">#include &lt;aeengine/eflags.h&gt;</span>
00028 <span class="preprocessor">#include &lt;aeengine/event.h&gt;</span>
00029 <span class="preprocessor">#include &lt;aeengine/frustumculler.h&gt;</span>
00030 <span class="preprocessor">#include &lt;aegeom/object.h&gt;</span>
00031 <span class="preprocessor">#include &lt;aegfx/texture.h&gt;</span>
00032 <span class="preprocessor">#include &lt;aereg/base.h&gt;</span>
00033 <span class="preprocessor">#include &lt;aereg/registry.h&gt;</span>
00034 
00035 <span class="keyword">class </span><a class="code" href="classaeCamera.php">aeCamera</a>;
00036 <span class="keyword">class </span><a class="code" href="classaeRegistry.php">aeRegistry</a>;
00037 
<a name="l00044"></a><a class="code" href="classaeEngine.php">00044</a> <span class="keyword">class </span><a class="code" href="classaeEngine.php">aeEngine</a>: <span class="keyword">public</span> <a class="code" href="classaeBase.php">aeBase</a> {
00045         AECF_CNDEF
00046 
00047  <span class="keyword">private</span>:
00048         <a class="code" href="classaeRegistry.php">aeRegistry</a> *aereg;
00049         <a class="code" href="classaeCamera.php">aeCamera</a> *camera;
00050         <a class="code" href="classaeFrustumCuller.php">aeFrustumCuller</a> *frustumCuller;
00051         SDL_Surface *screen;
00052         SDL_Event event;
00053         <span class="keywordtype">int</span> screenwidth;
00054         <span class="keywordtype">int</span> screenheight;
00055         <span class="keywordtype">int</span> screenbpp;
00056         <span class="keywordtype">int</span> videoflags;
00057         bool (*EventHandlerCallback)(<a class="code" href="structaeEvent.php">aeEvent</a> &amp;);
00058         <span class="keywordtype">bool</span> HaveEvHandlerCallback;
00059         <span class="keywordtype">bool</span> HasMultitext;
00060         <span class="keywordtype">bool</span> DoFakeMultitext;
00061         <span class="keywordtype">bool</span> done;
00062         <span class="keywordtype">bool</span> isactive;
00063         <a class="code" href="structaeEngineflags.php">aeEngineflags</a> *eflags;
00064 
00065         <span class="keywordtype">void</span> PrepareRender();
00066         <span class="keywordtype">void</span> FinishRender();
00067         <span class="keywordtype">void</span> BuildEventStruct(SDL_Event *, <a class="code" href="structaeEvent.php">aeEvent</a> *);
00068 
00069  <span class="keyword">public</span>:
00070         <a class="code" href="classaeEngine.php">aeEngine</a>(<a class="code" href="classaeRegistry.php">aeRegistry</a> *aeReg, <span class="keywordtype">int</span> width, <span class="keywordtype">int</span> height, <span class="keywordtype">int</span> vidflags);
00071         ~<a class="code" href="classaeEngine.php">aeEngine</a>();
00072 
<a name="l00074"></a><a class="code" href="classaeEngine.php#p0">00074</a>         <span class="keyword">static</span> <a class="code" href="classaeEngine.php">aeEngine</a> *<a class="code" href="classaeEngine.php#p0">self_ptr</a>;
00075 
00083         <span class="keywordtype">void</span> <a class="code" href="classaeEngine.php#a2">InitGL</a>();
00084 
00091         <span class="keywordtype">bool</span> <a class="code" href="classaeEngine.php#a3">OpenApplication</a>();
00092 
<a name="l00099"></a><a class="code" href="classaeEngine.php#a4">00099</a>         <span class="keywordtype">int</span> <a class="code" href="classaeEngine.php#a4">GetScreenWidth</a>()<span class="keyword"> const </span>{ <span class="keywordflow">return</span> screenwidth; }
00100 
<a name="l00107"></a><a class="code" href="classaeEngine.php#a5">00107</a>         <span class="keywordtype">int</span> <a class="code" href="classaeEngine.php#a5">GetScreenHeight</a>()<span class="keyword"> const </span>{ <span class="keywordflow">return</span> screenheight; }
00108 
<a name="l00116"></a><a class="code" href="classaeEngine.php#a6">00116</a>         <a class="code" href="classaeCamera.php">aeCamera</a> *<a class="code" href="classaeEngine.php#a6">GetCamera</a>()<span class="keyword"> const </span>{ <span class="keywordflow">return</span> camera; }
00117 
00126         <span class="keywordtype">bool</span> <a class="code" href="classaeEngine.php#a7">ResizeWindow</a>(<span class="keywordtype">int</span> new_width, <span class="keywordtype">int</span> new_height);
00127 
00133         <span class="keywordtype">void</span> <a class="code" href="classaeEngine.php#a8">Render</a>();
00134 
00142         <span class="keywordtype">bool</span> <a class="code" href="classaeEngine.php#a9">DefaultRunLoop</a>();
00143 
00153         <span class="keywordtype">void</span> <a class="code" href="classaeEngine.php#a10">AddObject</a>(<a class="code" href="classaeObject.php">aeObject</a> *);
00154 
00160         <span class="keywordtype">void</span> <a class="code" href="classaeEngine.php#a11">RegisterEventHandler</a>(aeEventHandlerCallback);
00161 
00167         <span class="keywordtype">void</span> <a class="code" href="classaeEngine.php#a12">AttachCamera</a>(<a class="code" href="classaeCamera.php">aeCamera</a> *);
00168 
00173         <span class="keywordtype">void</span> <a class="code" href="classaeEngine.php#a13">ToggleFullScreen</a>();
00174 
00183         <a class="code" href="classaeObject.php">aeObject</a> *<a class="code" href="classaeEngine.php#a14">FindObject</a>(<span class="keywordtype">unsigned</span> <span class="keywordtype">int</span>);
00184 
00193         <a class="code" href="classaeObject.php">aeObject</a> *<a class="code" href="classaeEngine.php#a15">FindObjectByName</a>(<span class="keywordtype">char</span> *);
00194 
00202         <span class="keywordtype">unsigned</span> <span class="keywordtype">int</span> <a class="code" href="classaeEngine.php#a16">GetObjectCount</a>();
00203 
00212         <a class="code" href="classaeTexture.php">aeTexture</a> *<a class="code" href="classaeEngine.php#a17">FindTexture</a>(<span class="keywordtype">unsigned</span> <span class="keywordtype">int</span>);
00213 
00222         <a class="code" href="classaeTexture.php">aeTexture</a> *<a class="code" href="classaeEngine.php#a18">FindTextureByName</a>(<span class="keywordtype">char</span> *);
00223 
00231         <span class="keywordtype">unsigned</span> <span class="keywordtype">int</span> <a class="code" href="classaeEngine.php#a19">GetTextureCount</a>();
00232 
00233         <span class="keywordtype">void</span> TempQuit();
00234 };
00235 
00236 <span class="preprocessor">#endif // __AELIB_AEENGINE_ENGINE_H__</span>
</pre></div><hr><address style="align: right;"><small>Generated on Sun Mar 2 01:14:21 2003 for AE Engine by
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border=0 
width=110 height=53></a>1.3-rc2 </small></address>
</body>
</html>
