<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>AE Object rendering modes</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.3-rc2 -->
<center>
<a class="qindex" href="index.php">Main Page</a> &nbsp; <a class="qindex" href="modules.php">Modules</a> &nbsp; <a class="qindex" href="hierarchy.php">Class Hierarchy</a> &nbsp; <a class="qindex" href="classes.php">Alphabetical List</a> &nbsp; <a class="qindex" href="annotated.php">Compound List</a> &nbsp; <a class="qindex" href="files.php">File List</a> &nbsp; <a class="qindex" href="functions.php">Compound Members</a> &nbsp; </center>
<hr><h1>AE Object rendering modes</h1>Rendering modes for different object types. 
<a href="#_details">More...</a><table border=0 cellpadding=0 cellspacing=0>
<tr><td></td></tr>
<tr><td colspan=2><br><h2>Enumerations</h2></td></tr>
<tr><td nowrap align=right valign=top>enum &nbsp;</td><td valign=bottom><a class="el" href="group__aeObjRenderingModes.php#a0">aeObjRenderingMode</a> { <br>
&nbsp;&nbsp;<a class="el" href="group__aeObjRenderingModes.php#a0a1">TRIANGLES_NORMAL</a>, 
<br>
&nbsp;&nbsp;<a class="el" href="group__aeObjRenderingModes.php#a0a2">TRIANGLES_STRIP</a>, 
<br>
&nbsp;&nbsp;<a class="el" href="group__aeObjRenderingModes.php#a0a3">TRIANGLES_FAN</a>, 
<br>
&nbsp;&nbsp;<a class="el" href="group__aeObjRenderingModes.php#a0a4">QUADS_NORMAL</a>, 
<br>
&nbsp;&nbsp;<a class="el" href="group__aeObjRenderingModes.php#a0a5">QUADS_STRIP</a>, 
<br>
&nbsp;&nbsp;<a class="el" href="group__aeObjRenderingModes.php#a0a6">LINES_NORMAL</a>, 
<br>
&nbsp;&nbsp;<a class="el" href="group__aeObjRenderingModes.php#a0a7">LINES_STRIP</a>, 
<br>
&nbsp;&nbsp;<a class="el" href="group__aeObjRenderingModes.php#a0a8">LINES_LOOP</a>, 
<br>
&nbsp;&nbsp;<a class="el" href="group__aeObjRenderingModes.php#a0a9">POLYGON_NORMAL</a>
<br>
 }</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Object rendering modes.</em> <a href="#a0">More...</a><em></em></font><br><br></td></tr>
</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
Rendering modes for different object types.
<p>
<hr><h2>Enumeration Type Documentation</h2>
<a name="a0" doxytag="object.h::aeObjRenderingMode"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> enum aeObjRenderingMode
      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Object rendering modes.
<p>
Used to specify a mode in which an object's vertices are interpreted. <dl compact><dt><b>Enumeration values: </b></dt><dd>
<table border=0 cellspacing=2 cellpadding=0>
<tr><td valign=top><em><a name="a0a1" doxytag="TRIANGLES_NORMAL"></a><em>TRIANGLES_NORMAL</em></em>&nbsp;</td><td>
Draw a triangle with 'GL_TRIANGLES' mode.
<p>
Treats each triplet of vertices as an independent triangle. Vertices 3n - 2, 3n - 1, and 3n define triangle n. <br>
<br>
</td></tr>
<tr><td valign=top><em><a name="a0a2" doxytag="TRIANGLES_STRIP"></a><em>TRIANGLES_STRIP</em></em>&nbsp;</td><td>
Draw a triangle with 'GL_TRIANGLE_STRIP' mode.
<p>
Draws a connected group of triangles. One triangle is defined for each vertex presented after the first two vertices. For odd n, vertices n, n + 1, and n + 2 define triangle n. For even n, vertices n + 1, n, and n + 2 define triangle n. N - 2 triangles are drawn. <br>
<br>
</td></tr>
<tr><td valign=top><em><a name="a0a3" doxytag="TRIANGLES_FAN"></a><em>TRIANGLES_FAN</em></em>&nbsp;</td><td>
Draw a triangle with 'GL_TRIANGLE_FAN' mode.
<p>
Draws a connected group of triangles. One triangle is defined for each vertex presented after the first two vertices. Vertices 1, n + 1, and n + 2 define triangle n. N - 2 triangles are drawn. <br>
<br>
</td></tr>
<tr><td valign=top><em><a name="a0a4" doxytag="QUADS_NORMAL"></a><em>QUADS_NORMAL</em></em>&nbsp;</td><td>
Draw a quad with 'GL_QUADS' mode.
<p>
Treats each group of four vertices as an independent quadrilateral. Vertices 4n - 3, 4n - 2, 4n - 1, and 4n define quadrilateral n. N / 4 quadrilaterals are drawn. <br>
<br>
</td></tr>
<tr><td valign=top><em><a name="a0a5" doxytag="QUADS_STRIP"></a><em>QUADS_STRIP</em></em>&nbsp;</td><td>
Draw a quad with 'GL_QUAD_STRIP' mode.
<p>
Draws a connected group of quadrilaterals. One quadrilateral is defined for each pair of vertices presented after the first pair. Vertices 2n - 1, 2n, 2n + 2, and 2n + 1 define quadrilateral n. N / 2 - 1 quadrilaterals are drawn. Note that the order in which vertices are used to construct a quadrilateral from strip data is different from that used with independent data. <br>
<br>
</td></tr>
<tr><td valign=top><em><a name="a0a6" doxytag="LINES_NORMAL"></a><em>LINES_NORMAL</em></em>&nbsp;</td><td>
Draw a line object with 'GL_LINES' mode.
<p>
Treats each pair of vertices as an independent line segment. Vertices 2n - 1 and 2n define line n. N/2 lines are drawn. <br>
<br>
</td></tr>
<tr><td valign=top><em><a name="a0a7" doxytag="LINES_STRIP"></a><em>LINES_STRIP</em></em>&nbsp;</td><td>
Draw a line object with 'GL_LINE_STRIP' mode.
<p>
Draws a connected group of line segments from the first vertex to the last. Vertices n and n + 1 define line n. <br>
<br>
</td></tr>
<tr><td valign=top><em><a name="a0a8" doxytag="LINES_LOOP"></a><em>LINES_LOOP</em></em>&nbsp;</td><td>
Draw a line object with 'GL_LINE_LOOP' mode.
<p>
Draws a connected group of line segments from the first vertex to the last, then back to the first. Vertices n and n+1 define line n. The last line, however, is defined by vertices N and 1. N lines are drawn. <br>
<br>
</td></tr>
<tr><td valign=top><em><a name="a0a9" doxytag="POLYGON_NORMAL"></a><em>POLYGON_NORMAL</em></em>&nbsp;</td><td>
Draw a polygon object with 'GL_POLYGON' mode.
<p>
Draws a single, convex polygon. Vertices 1 through N define this polygon.</td></tr>
</table>
</dl>

<p>
Definition at line <a class="el" href="object_8h-source.php#l00045">45</a> of file <a class="el" href="object_8h-source.php">object.h</a>.    </td>
  </tr>
</table>
<hr><address style="align: right;"><small>Generated on Sun Mar 2 01:14:24 2003 for AE Engine by
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border=0 
width=110 height=53></a>1.3-rc2 </small></address>
</body>
</html>
