<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>AE event structs and definitions.</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.3-rc2 -->
<center>
<a class="qindex" href="index.php">Main Page</a> &nbsp; <a class="qindex" href="modules.php">Modules</a> &nbsp; <a class="qindex" href="hierarchy.php">Class Hierarchy</a> &nbsp; <a class="qindex" href="classes.php">Alphabetical List</a> &nbsp; <a class="qindex" href="annotated.php">Compound List</a> &nbsp; <a class="qindex" href="files.php">File List</a> &nbsp; <a class="qindex" href="functions.php">Compound Members</a> &nbsp; </center>
<hr><h1>AE event structs and definitions.</h1>AE event structures and definitions. 
<a href="#_details">More...</a><table border=0 cellpadding=0 cellspacing=0>
<tr><td></td></tr>
<tr><td colspan=2><br><h2>Compounds</h2></td></tr>
<tr><td nowrap align=right valign=top>struct &nbsp;</td><td valign=bottom><a class="el" href="structaeActiveEvent.php">aeActiveEvent</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Holds info for app focus gain/lost event.</em> <a href="structaeActiveEvent.php#_details">More...</a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>struct &nbsp;</td><td valign=bottom><a class="el" href="structaeEvent.php">aeEvent</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>The AE event structure.</em> <a href="structaeEvent.php#_details">More...</a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>struct &nbsp;</td><td valign=bottom><a class="el" href="structaeEventCommand.php">aeEventCommand</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Event command struct.</em> <a href="structaeEventCommand.php#_details">More...</a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>struct &nbsp;</td><td valign=bottom><a class="el" href="structaeKeyboardEvent.php">aeKeyboardEvent</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Keyboard event struct.</em> <a href="structaeKeyboardEvent.php#_details">More...</a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>struct &nbsp;</td><td valign=bottom><a class="el" href="structaeKeySym.php">aeKeySym</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Key press info.</em> <a href="structaeKeySym.php#_details">More...</a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>struct &nbsp;</td><td valign=bottom><a class="el" href="structaeMouseButtonEvent.php">aeMouseButtonEvent</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Mouse button event struct.</em> <a href="structaeMouseButtonEvent.php#_details">More...</a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>struct &nbsp;</td><td valign=bottom><a class="el" href="structaeMouseMotionEvent.php">aeMouseMotionEvent</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Mouse motion event struct.</em> <a href="structaeMouseMotionEvent.php#_details">More...</a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>struct &nbsp;</td><td valign=bottom><a class="el" href="structaeQuitEvent.php">aeQuitEvent</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Quit event.</em> <a href="structaeQuitEvent.php#_details">More...</a><em></em></font><br><br></td></tr>
<tr><td colspan=2><br><h2>Typedefs</h2></td></tr>
<tr><td nowrap align=right valign=top><a name="a0" doxytag="eventstructs::aeKeyMod"></a>
typedef SDLMod&nbsp;</td><td valign=bottom><a class="el" href="group__eventstructs.php#a0">aeKeyMod</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Just a rename...</em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top><a name="a1" doxytag="eventstructs::aeEventHandlerCallback"></a>
typedef bool(*&nbsp;</td><td valign=bottom><a class="el" href="group__eventstructs.php#a1">aeEventHandlerCallback</a> )(<a class="el" href="structaeEvent.php">aeEvent</a> &amp;)</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Typedef for a event handler callback variable.</em></font><br><br></td></tr>
<tr><td colspan=2><br><h2>Enumerations</h2></td></tr>
<tr><td nowrap align=right valign=top>enum &nbsp;</td><td valign=bottom><a class="el" href="group__eventstructs.php#a2">aeKey</a> { <br>
&nbsp;&nbsp;<b>AEKEY_UNKNOWN</b> =  0, 
<br>
&nbsp;&nbsp;<b>AEKEY_FIRST</b> =  0, 
<br>
&nbsp;&nbsp;<b>AEKEY_BACKSPACE</b> =  8, 
<br>
&nbsp;&nbsp;<b>AEKEY_TAB</b> =  9, 
<br>
&nbsp;&nbsp;<b>AEKEY_CLEAR</b> =  12, 
<br>
&nbsp;&nbsp;<b>AEKEY_RETURN</b> =  13, 
<br>
&nbsp;&nbsp;<b>AEKEY_PAUSE</b> =  19, 
<br>
&nbsp;&nbsp;<b>AEKEY_ESCAPE</b> =  27, 
<br>
&nbsp;&nbsp;<b>AEKEY_SPACE</b> =  32, 
<br>
&nbsp;&nbsp;<b>AEKEY_EXCLAIM</b> =  33, 
<br>
&nbsp;&nbsp;<b>AEKEY_QUOTEDBL</b> =  34, 
<br>
&nbsp;&nbsp;<b>AEKEY_HASH</b> =  35, 
<br>
&nbsp;&nbsp;<b>AEKEY_DOLLAR</b> =  36, 
<br>
&nbsp;&nbsp;<b>AEKEY_AMPERSAND</b> =  38, 
<br>
&nbsp;&nbsp;<b>AEKEY_QUOTE</b> =  39, 
<br>
&nbsp;&nbsp;<b>AEKEY_LEFTPAREN</b> =  40, 
<br>
&nbsp;&nbsp;<b>AEKEY_RIGHTPAREN</b> =  41, 
<br>
&nbsp;&nbsp;<b>AEKEY_ASTERISK</b> =  42, 
<br>
&nbsp;&nbsp;<b>AEKEY_PLUS</b> =  43, 
<br>
&nbsp;&nbsp;<b>AEKEY_COMMA</b> =  44, 
<br>
&nbsp;&nbsp;<b>AEKEY_MINUS</b> =  45, 
<br>
&nbsp;&nbsp;<b>AEKEY_PERIOD</b> =  46, 
<br>
&nbsp;&nbsp;<b>AEKEY_SLASH</b> =  47, 
<br>
&nbsp;&nbsp;<b>AEKEY_0</b> =  48, 
<br>
&nbsp;&nbsp;<b>AEKEY_1</b> =  49, 
<br>
&nbsp;&nbsp;<b>AEKEY_2</b> =  50, 
<br>
&nbsp;&nbsp;<b>AEKEY_3</b> =  51, 
<br>
&nbsp;&nbsp;<b>AEKEY_4</b> =  52, 
<br>
&nbsp;&nbsp;<b>AEKEY_5</b> =  53, 
<br>
&nbsp;&nbsp;<b>AEKEY_6</b> =  54, 
<br>
&nbsp;&nbsp;<b>AEKEY_7</b> =  55, 
<br>
&nbsp;&nbsp;<b>AEKEY_8</b> =  56, 
<br>
&nbsp;&nbsp;<b>AEKEY_9</b> =  57, 
<br>
&nbsp;&nbsp;<b>AEKEY_COLON</b> =  58, 
<br>
&nbsp;&nbsp;<b>AEKEY_SEMICOLON</b> =  59, 
<br>
&nbsp;&nbsp;<b>AEKEY_LESS</b> =  60, 
<br>
&nbsp;&nbsp;<b>AEKEY_EQUALS</b> =  61, 
<br>
&nbsp;&nbsp;<b>AEKEY_GREATER</b> =  62, 
<br>
&nbsp;&nbsp;<b>AEKEY_QUESTION</b> =  63, 
<br>
&nbsp;&nbsp;<b>AEKEY_AT</b> =  64, 
<br>
&nbsp;&nbsp;<b>AEKEY_LEFTBRACKET</b> =  91, 
<br>
&nbsp;&nbsp;<b>AEKEY_BACKSLASH</b> =  92, 
<br>
&nbsp;&nbsp;<b>AEKEY_RIGHTBRACKET</b> =  93, 
<br>
&nbsp;&nbsp;<b>AEKEY_CARET</b> =  94, 
<br>
&nbsp;&nbsp;<b>AEKEY_UNDERSCORE</b> =  95, 
<br>
&nbsp;&nbsp;<b>AEKEY_BACKQUOTE</b> =  96, 
<br>
&nbsp;&nbsp;<b>AEKEY_a</b> =  97, 
<br>
&nbsp;&nbsp;<b>AEKEY_b</b> =  98, 
<br>
&nbsp;&nbsp;<b>AEKEY_c</b> =  99, 
<br>
&nbsp;&nbsp;<b>AEKEY_d</b> =  100, 
<br>
&nbsp;&nbsp;<b>AEKEY_e</b> =  101, 
<br>
&nbsp;&nbsp;<b>AEKEY_f</b> =  102, 
<br>
&nbsp;&nbsp;<b>AEKEY_g</b> =  103, 
<br>
&nbsp;&nbsp;<b>AEKEY_h</b> =  104, 
<br>
&nbsp;&nbsp;<b>AEKEY_i</b> =  105, 
<br>
&nbsp;&nbsp;<b>AEKEY_j</b> =  106, 
<br>
&nbsp;&nbsp;<b>AEKEY_k</b> =  107, 
<br>
&nbsp;&nbsp;<b>AEKEY_l</b> =  108, 
<br>
&nbsp;&nbsp;<b>AEKEY_m</b> =  109, 
<br>
&nbsp;&nbsp;<b>AEKEY_n</b> =  110, 
<br>
&nbsp;&nbsp;<b>AEKEY_o</b> =  111, 
<br>
&nbsp;&nbsp;<b>AEKEY_p</b> =  112, 
<br>
&nbsp;&nbsp;<b>AEKEY_q</b> =  113, 
<br>
&nbsp;&nbsp;<b>AEKEY_r</b> =  114, 
<br>
&nbsp;&nbsp;<b>AEKEY_s</b> =  115, 
<br>
&nbsp;&nbsp;<b>AEKEY_t</b> =  116, 
<br>
&nbsp;&nbsp;<b>AEKEY_u</b> =  117, 
<br>
&nbsp;&nbsp;<b>AEKEY_v</b> =  118, 
<br>
&nbsp;&nbsp;<b>AEKEY_w</b> =  119, 
<br>
&nbsp;&nbsp;<b>AEKEY_x</b> =  120, 
<br>
&nbsp;&nbsp;<b>AEKEY_y</b> =  121, 
<br>
&nbsp;&nbsp;<b>AEKEY_z</b> =  122, 
<br>
&nbsp;&nbsp;<b>AEKEY_DELETE</b> =  127, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_0</b> =  160, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_1</b> =  161, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_2</b> =  162, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_3</b> =  163, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_4</b> =  164, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_5</b> =  165, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_6</b> =  166, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_7</b> =  167, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_8</b> =  168, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_9</b> =  169, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_10</b> =  170, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_11</b> =  171, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_12</b> =  172, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_13</b> =  173, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_14</b> =  174, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_15</b> =  175, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_16</b> =  176, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_17</b> =  177, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_18</b> =  178, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_19</b> =  179, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_20</b> =  180, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_21</b> =  181, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_22</b> =  182, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_23</b> =  183, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_24</b> =  184, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_25</b> =  185, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_26</b> =  186, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_27</b> =  187, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_28</b> =  188, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_29</b> =  189, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_30</b> =  190, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_31</b> =  191, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_32</b> =  192, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_33</b> =  193, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_34</b> =  194, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_35</b> =  195, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_36</b> =  196, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_37</b> =  197, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_38</b> =  198, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_39</b> =  199, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_40</b> =  200, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_41</b> =  201, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_42</b> =  202, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_43</b> =  203, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_44</b> =  204, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_45</b> =  205, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_46</b> =  206, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_47</b> =  207, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_48</b> =  208, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_49</b> =  209, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_50</b> =  210, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_51</b> =  211, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_52</b> =  212, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_53</b> =  213, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_54</b> =  214, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_55</b> =  215, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_56</b> =  216, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_57</b> =  217, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_58</b> =  218, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_59</b> =  219, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_60</b> =  220, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_61</b> =  221, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_62</b> =  222, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_63</b> =  223, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_64</b> =  224, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_65</b> =  225, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_66</b> =  226, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_67</b> =  227, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_68</b> =  228, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_69</b> =  229, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_70</b> =  230, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_71</b> =  231, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_72</b> =  232, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_73</b> =  233, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_74</b> =  234, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_75</b> =  235, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_76</b> =  236, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_77</b> =  237, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_78</b> =  238, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_79</b> =  239, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_80</b> =  240, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_81</b> =  241, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_82</b> =  242, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_83</b> =  243, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_84</b> =  244, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_85</b> =  245, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_86</b> =  246, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_87</b> =  247, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_88</b> =  248, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_89</b> =  249, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_90</b> =  250, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_91</b> =  251, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_92</b> =  252, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_93</b> =  253, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_94</b> =  254, 
<br>
&nbsp;&nbsp;<b>AEKEY_WORLD_95</b> =  255, 
<br>
&nbsp;&nbsp;<b>AEKEY_KP0</b> =  256, 
<br>
&nbsp;&nbsp;<b>AEKEY_KP1</b> =  257, 
<br>
&nbsp;&nbsp;<b>AEKEY_KP2</b> =  258, 
<br>
&nbsp;&nbsp;<b>AEKEY_KP3</b> =  259, 
<br>
&nbsp;&nbsp;<b>AEKEY_KP4</b> =  260, 
<br>
&nbsp;&nbsp;<b>AEKEY_KP5</b> =  261, 
<br>
&nbsp;&nbsp;<b>AEKEY_KP6</b> =  262, 
<br>
&nbsp;&nbsp;<b>AEKEY_KP7</b> =  263, 
<br>
&nbsp;&nbsp;<b>AEKEY_KP8</b> =  264, 
<br>
&nbsp;&nbsp;<b>AEKEY_KP9</b> =  265, 
<br>
&nbsp;&nbsp;<b>AEKEY_KP_PERIOD</b> =  266, 
<br>
&nbsp;&nbsp;<b>AEKEY_KP_DIVIDE</b> =  267, 
<br>
&nbsp;&nbsp;<b>AEKEY_KP_MULTIPLY</b> =  268, 
<br>
&nbsp;&nbsp;<b>AEKEY_KP_MINUS</b> =  269, 
<br>
&nbsp;&nbsp;<b>AEKEY_KP_PLUS</b> =  270, 
<br>
&nbsp;&nbsp;<b>AEKEY_KP_ENTER</b> =  271, 
<br>
&nbsp;&nbsp;<b>AEKEY_KP_EQUALS</b> =  272, 
<br>
&nbsp;&nbsp;<b>AEKEY_UP</b> =  273, 
<br>
&nbsp;&nbsp;<b>AEKEY_DOWN</b> =  274, 
<br>
&nbsp;&nbsp;<b>AEKEY_RIGHT</b> =  275, 
<br>
&nbsp;&nbsp;<b>AEKEY_LEFT</b> =  276, 
<br>
&nbsp;&nbsp;<b>AEKEY_INSERT</b> =  277, 
<br>
&nbsp;&nbsp;<b>AEKEY_HOME</b> =  278, 
<br>
&nbsp;&nbsp;<b>AEKEY_END</b> =  279, 
<br>
&nbsp;&nbsp;<b>AEKEY_PAGEUP</b> =  280, 
<br>
&nbsp;&nbsp;<b>AEKEY_PAGEDOWN</b> =  281, 
<br>
&nbsp;&nbsp;<b>AEKEY_F1</b> =  282, 
<br>
&nbsp;&nbsp;<b>AEKEY_F2</b> =  283, 
<br>
&nbsp;&nbsp;<b>AEKEY_F3</b> =  284, 
<br>
&nbsp;&nbsp;<b>AEKEY_F4</b> =  285, 
<br>
&nbsp;&nbsp;<b>AEKEY_F5</b> =  286, 
<br>
&nbsp;&nbsp;<b>AEKEY_F6</b> =  287, 
<br>
&nbsp;&nbsp;<b>AEKEY_F7</b> =  288, 
<br>
&nbsp;&nbsp;<b>AEKEY_F8</b> =  289, 
<br>
&nbsp;&nbsp;<b>AEKEY_F9</b> =  290, 
<br>
&nbsp;&nbsp;<b>AEKEY_F10</b> =  291, 
<br>
&nbsp;&nbsp;<b>AEKEY_F11</b> =  292, 
<br>
&nbsp;&nbsp;<b>AEKEY_F12</b> =  293, 
<br>
&nbsp;&nbsp;<b>AEKEY_F13</b> =  294, 
<br>
&nbsp;&nbsp;<b>AEKEY_F14</b> =  295, 
<br>
&nbsp;&nbsp;<b>AEKEY_F15</b> =  296, 
<br>
&nbsp;&nbsp;<b>AEKEY_NUMLOCK</b> =  300, 
<br>
&nbsp;&nbsp;<b>AEKEY_CAPSLOCK</b> =  301, 
<br>
&nbsp;&nbsp;<b>AEKEY_SCROLLOCK</b> =  302, 
<br>
&nbsp;&nbsp;<b>AEKEY_RSHIFT</b> =  303, 
<br>
&nbsp;&nbsp;<b>AEKEY_LSHIFT</b> =  304, 
<br>
&nbsp;&nbsp;<b>AEKEY_RCTRL</b> =  305, 
<br>
&nbsp;&nbsp;<b>AEKEY_LCTRL</b> =  306, 
<br>
&nbsp;&nbsp;<b>AEKEY_RALT</b> =  307, 
<br>
&nbsp;&nbsp;<b>AEKEY_LALT</b> =  308, 
<br>
&nbsp;&nbsp;<b>AEKEY_RMETA</b> =  309, 
<br>
&nbsp;&nbsp;<b>AEKEY_LMETA</b> =  310, 
<br>
&nbsp;&nbsp;<b>AEKEY_LSUPER</b> =  311, 
<br>
&nbsp;&nbsp;<b>AEKEY_RSUPER</b> =  312, 
<br>
&nbsp;&nbsp;<b>AEKEY_MODE</b> =  313, 
<br>
&nbsp;&nbsp;<b>AEKEY_COMPOSE</b> =  314, 
<br>
&nbsp;&nbsp;<b>AEKEY_HELP</b> =  315, 
<br>
&nbsp;&nbsp;<b>AEKEY_PRINT</b> =  316, 
<br>
&nbsp;&nbsp;<b>AEKEY_SYSREQ</b> =  317, 
<br>
&nbsp;&nbsp;<b>AEKEY_BREAK</b> =  318, 
<br>
&nbsp;&nbsp;<b>AEKEY_MENU</b> =  319, 
<br>
&nbsp;&nbsp;<b>AEKEY_POWER</b> =  320, 
<br>
&nbsp;&nbsp;<b>AEKEY_EURO</b> =  321, 
<br>
&nbsp;&nbsp;<b>AEKEY_UNDO</b> =  322, 
<br>
&nbsp;&nbsp;<b>AEKEY_LAST</b>
<br>
 }</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Key definition table.</em> <a href="#a2">More...</a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>enum &nbsp;</td><td valign=bottom><a class="el" href="group__eventstructs.php#a3">aeEventType</a> { <br>
&nbsp;&nbsp;<b>aeevActiveEvent</b>, 
<br>
&nbsp;&nbsp;<b>aeevBroadcast</b>, 
<br>
&nbsp;&nbsp;<b>aeevKeyDown</b>, 
<br>
&nbsp;&nbsp;<b>aeevKeyUp</b>, 
<br>
&nbsp;&nbsp;<b>aeevMouseMotion</b>, 
<br>
&nbsp;&nbsp;<b>aeevMouseButtonDown</b>, 
<br>
&nbsp;&nbsp;<b>aeevMouseButtonUp</b>, 
<br>
&nbsp;&nbsp;<b>aeevQuit</b>
<br>
 }</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Event type codes. Used to indentify the type of an event occuring.</em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>enum &nbsp;</td><td valign=bottom><a class="el" href="group__eventstructs.php#a4">aeEventCmdCode</a> { <br>
&nbsp;&nbsp;<b>aecmdPreFrame</b>, 
<br>
&nbsp;&nbsp;<b>aecmdProcessFrame</b>, 
<br>
&nbsp;&nbsp;<b>aecmdPostFrame</b>, 
<br>
&nbsp;&nbsp;<b>aecmdToggleFullscreen</b>
<br>
 }</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Event command codes.</em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>enum &nbsp;</td><td valign=bottom><a class="el" href="group__eventstructs.php#a5">aeAppActiveState</a> { <br>
&nbsp;&nbsp;<b>aeAppMouseFocus</b>, 
<br>
&nbsp;&nbsp;<b>aeAppInputFocus</b>, 
<br>
&nbsp;&nbsp;<b>aeAppActive</b>
<br>
 }</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Application focus states.</em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>enum &nbsp;</td><td valign=bottom><a class="el" href="group__eventstructs.php#a6">aeButtonState</a> { <br>
&nbsp;&nbsp;<b>aePressed</b>, 
<br>
&nbsp;&nbsp;<b>aeReleased</b>
<br>
 }</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Button states for press/release.</em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>enum &nbsp;</td><td valign=bottom><a class="el" href="group__eventstructs.php#a7">aeMouseButton</a> { <br>
&nbsp;&nbsp;<b>aeButtonLeft</b> =  1, 
<br>
&nbsp;&nbsp;<b>aeButtonMiddle</b> =  2, 
<br>
&nbsp;&nbsp;<b>aeButtonRight</b> =  3
<br>
 }</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Mouse button definitions.</em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>enum &nbsp;</td><td valign=bottom><a class="el" href="group__eventstructs.php#a8">aeMouseButtonState</a> { <br>
&nbsp;&nbsp;<b>aeNonePressed</b> =  0, 
<br>
&nbsp;&nbsp;<b>aeLeftPressed</b> =  1, 
<br>
&nbsp;&nbsp;<b>aeMiddlePressed</b> =  2, 
<br>
&nbsp;&nbsp;<b>aeRightPressed</b> =  3
<br>
 }</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Mouse button states for press/release.</em></font><br><br></td></tr>
</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
AE event structures and definitions.
<p>
<hr><h2>Enumeration Type Documentation</h2>
<a name="a2" doxytag="event.h::aeKey"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> enum aeKey
      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Key definition table.
<p>
This is essentially the same as SDLKEY_*, the only change is in the name (AEKEY_*). 
<p>
Definition at line <a class="el" href="event_8h-source.php#l00037">37</a> of file <a class="el" href="event_8h-source.php">event.h</a>.    </td>
  </tr>
</table>
<hr><address style="align: right;"><small>Generated on Sun Mar 2 01:14:24 2003 for AE Engine by
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border=0 
width=110 height=53></a>1.3-rc2 </small></address>
</body>
</html>
