<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>AE typedefs</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.3-rc2 -->
<center>
<a class="qindex" href="index.php">Main Page</a> &nbsp; <a class="qindex" href="modules.php">Modules</a> &nbsp; <a class="qindex" href="hierarchy.php">Class Hierarchy</a> &nbsp; <a class="qindex" href="classes.php">Alphabetical List</a> &nbsp; <a class="qindex" href="annotated.php">Compound List</a> &nbsp; <a class="qindex" href="files.php">File List</a> &nbsp; <a class="qindex" href="functions.php">Compound Members</a> &nbsp; </center>
<hr><h1>AE typedefs</h1>Varius typedeffings. 
<a href="#_details">More...</a><table border=0 cellpadding=0 cellspacing=0>
<tr><td></td></tr>
<tr><td colspan=2><br><h2>Typedefs</h2></td></tr>
<tr><td nowrap align=right valign=top><a name="a0" doxytag="aetypedefs::uint8"></a>
typedef unsigned char&nbsp;</td><td valign=bottom><a class="el" href="group__aetypedefs.php#a0">uint8</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Unsigned 1-byte integer.</em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top><a name="a1" doxytag="aetypedefs::sint8"></a>
typedef signed char&nbsp;</td><td valign=bottom><a class="el" href="group__aetypedefs.php#a1">sint8</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Signed 1-byte integer.</em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top><a name="a2" doxytag="aetypedefs::uint16"></a>
typedef unsigned short&nbsp;</td><td valign=bottom><a class="el" href="group__aetypedefs.php#a2">uint16</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Unsigned 2-byte integer.</em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top><a name="a3" doxytag="aetypedefs::sint16"></a>
typedef signed short&nbsp;</td><td valign=bottom><a class="el" href="group__aetypedefs.php#a3">sint16</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Signed 2-byte integer.</em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top><a name="a4" doxytag="aetypedefs::uint32"></a>
typedef unsigned int&nbsp;</td><td valign=bottom><a class="el" href="group__aetypedefs.php#a4">uint32</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Unsigned 4-byte integer.</em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top><a name="a5" doxytag="aetypedefs::sint32"></a>
typedef signed int&nbsp;</td><td valign=bottom><a class="el" href="group__aetypedefs.php#a5">sint32</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Signed 4-byte integer.</em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top><a name="a6" doxytag="aetypedefs::aeBlockDescriptor_map"></a>
typedef std::map&lt; void *,<br>
 <a class="el" href="classaeBlockDescriptor.php">aeBlockDescriptor</a> * &gt;&nbsp;</td><td valign=bottom><a class="el" href="group__aetypedefs.php#a6">aeBlockDescriptor_map</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>This map maps pointers to blockdescriptors.</em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top><a name="a7" doxytag="aetypedefs::aeVector3_vector"></a>
typedef std::vector&lt; <a class="el" href="classaeVector3.php">aeVector3</a> &gt;&nbsp;</td><td valign=bottom><a class="el" href="group__aetypedefs.php#a7">aeVector3_vector</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>This vector contains <a class="el" href="classaeVector3.php">aeVector3</a> instances.</em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top><a name="a8" doxytag="aetypedefs::aeTexCoord2_vector"></a>
typedef std::vector&lt; <a class="el" href="classaeTexCoord2.php">aeTexCoord2</a> &gt;&nbsp;</td><td valign=bottom><a class="el" href="group__aetypedefs.php#a8">aeTexCoord2_vector</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>This vector contains <a class="el" href="classaeTexCoord2.php">aeTexCoord2</a> instances.</em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top><a name="a9" doxytag="aetypedefs::aeColor4_vector"></a>
typedef std::vector&lt; <a class="el" href="classaeColor4.php">aeColor4</a> &gt;&nbsp;</td><td valign=bottom><a class="el" href="group__aetypedefs.php#a9">aeColor4_vector</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>This vector contains <a class="el" href="classaeColor4.php">aeColor4</a> instances.</em></font><br><br></td></tr>
</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
Varius typedeffings.
<p>
<hr><address style="align: right;"><small>Generated on Sun Mar 2 01:14:24 2003 for AE Engine by
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border=0 
width=110 height=53></a>1.3-rc2 </small></address>
</body>
</html>
