<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>AE model type enumerations</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.3-rc2 -->
<center>
<a class="qindex" href="index.php">Main Page</a> &nbsp; <a class="qindex" href="modules.php">Modules</a> &nbsp; <a class="qindex" href="hierarchy.php">Class Hierarchy</a> &nbsp; <a class="qindex" href="classes.php">Alphabetical List</a> &nbsp; <a class="qindex" href="annotated.php">Compound List</a> &nbsp; <a class="qindex" href="files.php">File List</a> &nbsp; <a class="qindex" href="functions.php">Compound Members</a> &nbsp; </center>
<hr><h1>AE model type enumerations</h1>AE Model type definitions. 
<a href="#_details">More...</a><table border=0 cellpadding=0 cellspacing=0>
<tr><td></td></tr>
<tr><td colspan=2><br><h2>Enumerations</h2></td></tr>
<tr><td nowrap align=right valign=top>enum &nbsp;</td><td valign=bottom><a class="el" href="group__mdltypes.php#a0">aeModelType</a> { <br>
&nbsp;&nbsp;<a class="el" href="group__mdltypes.php#a0a1">AE_MODEL_MD2</a>, 
<br>
&nbsp;&nbsp;<a class="el" href="group__mdltypes.php#a0a2">AE_MODEL_UNKNOWN</a>
<br>
 }</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>AE model type enumerations.</em> <a href="#a0">More...</a><em></em></font><br><br></td></tr>
</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
AE Model type definitions.
<p>
<hr><h2>Enumeration Type Documentation</h2>
<a name="a0" doxytag="mdlldr.h::aeModelType"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> enum aeModelType
      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
AE model type enumerations.
<p>
<dl compact><dt><b>Enumeration values: </b></dt><dd>
<table border=0 cellspacing=2 cellpadding=0>
<tr><td valign=top><em><a name="a0a1" doxytag="AE_MODEL_MD2"></a><em>AE_MODEL_MD2</em></em>&nbsp;</td><td>
A Quake2 MD2 model.</td></tr>
<tr><td valign=top><em><a name="a0a2" doxytag="AE_MODEL_UNKNOWN"></a><em>AE_MODEL_UNKNOWN</em></em>&nbsp;</td><td>
An unknown model type.</td></tr>
</table>
</dl>

<p>
Definition at line <a class="el" href="mdlldr_8h-source.php#l00039">39</a> of file <a class="el" href="mdlldr_8h-source.php">mdlldr.h</a>.    </td>
  </tr>
</table>
<hr><address style="align: right;"><small>Generated on Sun Mar 2 01:14:24 2003 for AE Engine by
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border=0 
width=110 height=53></a>1.3-rc2 </small></address>
</body>
</html>
