<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>AE texture loader image structures</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.3-rc2 -->
<center>
<a class="qindex" href="index.php">Main Page</a> &nbsp; <a class="qindex" href="modules.php">Modules</a> &nbsp; <a class="qindex" href="hierarchy.php">Class Hierarchy</a> &nbsp; <a class="qindex" href="classes.php">Alphabetical List</a> &nbsp; <a class="qindex" href="annotated.php">Compound List</a> &nbsp; <a class="qindex" href="files.php">File List</a> &nbsp; <a class="qindex" href="functions.php">Compound Members</a> &nbsp; </center>
<hr><h1>AE texture loader image structures</h1>AE texture loader image structures and definitions. 
<a href="#_details">More...</a><table border=0 cellpadding=0 cellspacing=0>
<tr><td></td></tr>
<tr><td colspan=2><br><h2>Compounds</h2></td></tr>
<tr><td nowrap align=right valign=top>struct &nbsp;</td><td valign=bottom><a class="el" href="structbmpFileHeader.php">bmpFileHeader</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>BITMAPFILEHEADER struct.</em> <a href="structbmpFileHeader.php#_details">More...</a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>struct &nbsp;</td><td valign=bottom><a class="el" href="structbmpHeader.php">bmpHeader</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>BITMAPINFOHEADER struct.</em> <a href="structbmpHeader.php#_details">More...</a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>struct &nbsp;</td><td valign=bottom><a class="el" href="structpcxHeader.php">pcxHeader</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>(A partial) PCX file header.</em> <a href="structpcxHeader.php#_details">More...</a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>struct &nbsp;</td><td valign=bottom><a class="el" href="structtgaHeader.php">tgaHeader</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>TGA file header.</em> <a href="structtgaHeader.php#_details">More...</a><em></em></font><br><br></td></tr>
<tr><td colspan=2><br><h2>Enumerations</h2></td></tr>
<tr><td nowrap align=right valign=top>enum &nbsp;</td><td valign=bottom><a class="el" href="group__txtldrstructs.php#a0">TGATypes</a> { <br>
&nbsp;&nbsp;<a class="el" href="group__txtldrstructs.php#a0a1">TGA_RGB</a> =  2, 
<br>
&nbsp;&nbsp;<a class="el" href="group__txtldrstructs.php#a0a2">TGA_GREY</a> =  3, 
<br>
&nbsp;&nbsp;<a class="el" href="group__txtldrstructs.php#a0a3">TGA_RLERGB</a> =  10, 
<br>
&nbsp;&nbsp;<a class="el" href="group__txtldrstructs.php#a0a4">TGA_RLEGREY</a> =  11
<br>
 }</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>TGA types.</em> <a href="#a0">More...</a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>enum &nbsp;</td><td valign=bottom><a class="el" href="group__txtldrstructs.php#a1">aeTextureType</a> { <br>
&nbsp;&nbsp;<a class="el" href="group__txtldrstructs.php#a1a5">AE_TEXTURE_BMP</a>, 
<br>
&nbsp;&nbsp;<a class="el" href="group__txtldrstructs.php#a1a6">AE_TEXTURE_PCX</a>, 
<br>
&nbsp;&nbsp;<a class="el" href="group__txtldrstructs.php#a1a7">AE_TEXTURE_TGA</a>, 
<br>
&nbsp;&nbsp;<a class="el" href="group__txtldrstructs.php#a1a8">AE_TEXTURE_UNKNOWN</a>
<br>
 }</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Supported texture types.</em> <a href="#a1">More...</a><em></em></font><br><br></td></tr>
</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
AE texture loader image structures and definitions.
<p>
<hr><h2>Enumeration Type Documentation</h2>
<a name="a1" doxytag="txtldr.h::aeTextureType"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> enum aeTextureType
      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Supported texture types.
<p>
<dl compact><dt><b>Enumeration values: </b></dt><dd>
<table border=0 cellspacing=2 cellpadding=0>
<tr><td valign=top><em><a name="a1a5" doxytag="AE_TEXTURE_BMP"></a><em>AE_TEXTURE_BMP</em></em>&nbsp;</td><td>
BMP image.</td></tr>
<tr><td valign=top><em><a name="a1a6" doxytag="AE_TEXTURE_PCX"></a><em>AE_TEXTURE_PCX</em></em>&nbsp;</td><td>
PCX image.</td></tr>
<tr><td valign=top><em><a name="a1a7" doxytag="AE_TEXTURE_TGA"></a><em>AE_TEXTURE_TGA</em></em>&nbsp;</td><td>
TGA image.</td></tr>
<tr><td valign=top><em><a name="a1a8" doxytag="AE_TEXTURE_UNKNOWN"></a><em>AE_TEXTURE_UNKNOWN</em></em>&nbsp;</td><td>
Unknown image.</td></tr>
</table>
</dl>

<p>
Definition at line <a class="el" href="txtldr_8h-source.php#l00050">50</a> of file <a class="el" href="txtldr_8h-source.php">txtldr.h</a>.    </td>
  </tr>
</table>
<a name="a0" doxytag="txtldr.h::TGATypes"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> enum TGATypes
      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
TGA types.
<p>
<dl compact><dt><b>Enumeration values: </b></dt><dd>
<table border=0 cellspacing=2 cellpadding=0>
<tr><td valign=top><em><a name="a0a1" doxytag="TGA_RGB"></a><em>TGA_RGB</em></em>&nbsp;</td><td>
Uncompressed RGB image.</td></tr>
<tr><td valign=top><em><a name="a0a2" doxytag="TGA_GREY"></a><em>TGA_GREY</em></em>&nbsp;</td><td>
Uncompressed greyscale image.</td></tr>
<tr><td valign=top><em><a name="a0a3" doxytag="TGA_RLERGB"></a><em>TGA_RLERGB</em></em>&nbsp;</td><td>
Run-lenght encoded RGB image.</td></tr>
<tr><td valign=top><em><a name="a0a4" doxytag="TGA_RLEGREY"></a><em>TGA_RLEGREY</em></em>&nbsp;</td><td>
Run-lenght encoded greyscale image.</td></tr>
</table>
</dl>

<p>
Definition at line <a class="el" href="txtldr_8h-source.php#l00038">38</a> of file <a class="el" href="txtldr_8h-source.php">txtldr.h</a>.    </td>
  </tr>
</table>
<hr><address style="align: right;"><small>Generated on Sun Mar 2 01:14:24 2003 for AE Engine by
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border=0 
width=110 height=53></a>1.3-rc2 </small></address>
</body>
</html>
