<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>AE model loader structures</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.3-rc2 -->
<center>
<a class="qindex" href="index.php">Main Page</a> &nbsp; <a class="qindex" href="modules.php">Modules</a> &nbsp; <a class="qindex" href="hierarchy.php">Class Hierarchy</a> &nbsp; <a class="qindex" href="classes.php">Alphabetical List</a> &nbsp; <a class="qindex" href="annotated.php">Compound List</a> &nbsp; <a class="qindex" href="files.php">File List</a> &nbsp; <a class="qindex" href="functions.php">Compound Members</a> &nbsp; </center>
<hr><h1>AE model loader structures</h1>Various structures used by the model loader. 
<a href="#_details">More...</a><table border=0 cellpadding=0 cellspacing=0>
<tr><td></td></tr>
<tr><td colspan=2><br><h2>Compounds</h2></td></tr>
<tr><td nowrap align=right valign=top>struct &nbsp;</td><td valign=bottom><a class="el" href="structframe__t.php">frame_t</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>A single frame structure.</em> <a href="structframe__t.php#_details">More...</a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>struct &nbsp;</td><td valign=bottom><a class="el" href="structframePoint__t.php">framePoint_t</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>A single frame point structure.</em> <a href="structframePoint__t.php#_details">More...</a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>struct &nbsp;</td><td valign=bottom><a class="el" href="structmd2Header__t.php">md2Header_t</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>A MD2 header structure.</em> <a href="structmd2Header__t.php#_details">More...</a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>struct &nbsp;</td><td valign=bottom><a class="el" href="structmesh__t.php">mesh_t</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>A mesh structure.</em> <a href="structmesh__t.php#_details">More...</a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>struct &nbsp;</td><td valign=bottom><a class="el" href="structstIndex__t.php">stIndex_t</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>A texture coordinate index structure.</em> <a href="structstIndex__t.php#_details">More...</a><em></em></font><br><br></td></tr>
<tr><td colspan=2><br><h2>Enumerations</h2></td></tr>
<tr><td nowrap align=right valign=top>enum &nbsp;</td><td valign=bottom><a class="el" href="group__mdlldrstructs.php#a0">modelState_t</a> { <br>
&nbsp;&nbsp;<b>MODEL_IDLE</b>, 
<br>
&nbsp;&nbsp;<b>MODEL_CROUCH</b>, 
<br>
&nbsp;&nbsp;<b>MODEL_RUN</b>, 
<br>
&nbsp;&nbsp;<b>MODEL_JUMP</b>
<br>
 }</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>A model state structure.</em></font><br><br></td></tr>
</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
Various structures used by the model loader.
<p>
<hr><address style="align: right;"><small>Generated on Sun Mar 2 01:14:24 2003 for AE Engine by
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border=0 
width=110 height=53></a>1.3-rc2 </small></address>
</body>
</html>
