<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>object.h Source File</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.3-rc2 -->
<center>
<a class="qindex" href="index.php">Main Page</a> &nbsp; <a class="qindex" href="modules.php">Modules</a> &nbsp; <a class="qindex" href="hierarchy.php">Class Hierarchy</a> &nbsp; <a class="qindex" href="classes.php">Alphabetical List</a> &nbsp; <a class="qindex" href="annotated.php">Compound List</a> &nbsp; <a class="qindex" href="files.php">File List</a> &nbsp; <a class="qindex" href="functions.php">Compound Members</a> &nbsp; </center>
<hr><h1>object.h</h1><div class="fragment"><pre>00001 <span class="comment">/*</span>
00002 <span class="comment"> *  AE Engine</span>
00003 <span class="comment"> *</span>
00004 <span class="comment"> *  Copyright (C) 2003 Riku "Rakkis" Nurminen</span>
00005 <span class="comment"> *</span>
00006 <span class="comment"> *  This program is free software; you can redistribute it and/or modify</span>
00007 <span class="comment"> *  it under the terms of the GNU General Public License as published by</span>
00008 <span class="comment"> *  the Free Software Foundation; either version 2 of the License, or</span>
00009 <span class="comment"> *  (at your option) any later version.</span>
00010 <span class="comment"> *</span>
00011 <span class="comment"> *  This program is distributed in the hope that it will be useful,</span>
00012 <span class="comment"> *  but WITHOUT ANY WARRANTY; without even the implied warranty of</span>
00013 <span class="comment"> *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the</span>
00014 <span class="comment"> *  GNU General Public License for more details.</span>
00015 <span class="comment"> *</span>
00016 <span class="comment"> *  You should have received a copy of the GNU General Public License</span>
00017 <span class="comment"> *  along with this program; if not, write to the Free Software</span>
00018 <span class="comment"> *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA</span>
00019 <span class="comment"> *</span>
00020 <span class="comment"> */</span>
00021 
00022 <span class="preprocessor">#ifndef __AELIB_AEGEOM_OBJECT_H__</span>
00023 <span class="preprocessor"></span><span class="preprocessor">#define __AELIB_AEGEOM_OBJECT_H__</span>
00024 <span class="preprocessor"></span>
00025 <span class="preprocessor">#define ONLY_INCLUDE_STD</span>
00026 <span class="preprocessor"></span><span class="preprocessor">#include &lt;aedefs.h&gt;</span>
00027 <span class="preprocessor">#undef ONLY_INCLUDE_STD</span>
00028 <span class="preprocessor"></span><span class="preprocessor">#include &lt;aeengine/eflags.h&gt;</span>
00029 <span class="preprocessor">#include &lt;aegeom/vector3.h&gt;</span>
00030 <span class="preprocessor">#include &lt;aegfx/color3.h&gt;</span>
00031 <span class="preprocessor">#include &lt;aegfx/color4.h&gt;</span>
00032 <span class="preprocessor">#include &lt;aegfx/material.h&gt;</span>
00033 <span class="preprocessor">#include &lt;aegfx/texcoord2.h&gt;</span>
00034 <span class="preprocessor">#include &lt;aereg/base.h&gt;</span>
00035 
<a name="l00045"></a><a class="code" href="group__aeObjRenderingModes.php#a0">00045</a> <span class="keyword">enum</span> <a class="code" href="group__aeObjRenderingModes.php#a0">aeObjRenderingMode</a> {
00047 
00053         <a class="code" href="group__aeObjRenderingModes.php#a0a1">TRIANGLES_NORMAL</a>,
00055 
00062         <a class="code" href="group__aeObjRenderingModes.php#a0a2">TRIANGLES_STRIP</a>,
00064 
00071         <a class="code" href="group__aeObjRenderingModes.php#a0a3">TRIANGLES_FAN</a>,
00072 
00074 
00080         <a class="code" href="group__aeObjRenderingModes.php#a0a4">QUADS_NORMAL</a>,
00082 
00091         <a class="code" href="group__aeObjRenderingModes.php#a0a5">QUADS_STRIP</a>,
00092 
00094 
00099         <a class="code" href="group__aeObjRenderingModes.php#a0a6">LINES_NORMAL</a>,
00101 
00106         <a class="code" href="group__aeObjRenderingModes.php#a0a7">LINES_STRIP</a>,
00108 
00114         <a class="code" href="group__aeObjRenderingModes.php#a0a8">LINES_LOOP</a>,
00115 
00117 
00120         <a class="code" href="group__aeObjRenderingModes.php#a0a9">POLYGON_NORMAL</a>
00121 };
00122 
<a name="l00129"></a><a class="code" href="classaeObject.php">00129</a> <span class="keyword">class </span><a class="code" href="classaeObject.php">aeObject</a>: <span class="keyword">public</span> <a class="code" href="classaeBase.php">aeBase</a> {
00130  <span class="keyword">protected</span>:
00131         std::vector&lt;aeVector3&gt; *vertexList;
00132         std::vector&lt;aeColor4&gt; *vertexColorList;
00133         std::vector&lt;aeTexCoord2&gt; *vertexTexcoordList;
00134         <a class="code" href="classaeVector3.php">aeVector3</a> origin;
00135         <a class="code" href="classaeColor4.php">aeColor4</a> currentVertexColor;
00136         <a class="code" href="classaeTexCoord2.php">aeTexCoord2</a> currentVertexTexcoord;
00137         <span class="keywordtype">bool</span> hasMaterial;
00138         <a class="code" href="classaeMaterial.php">aeMaterial</a> *material;
00139         <span class="keywordtype">char</span> *objName;
00140         <span class="keywordtype">bool</span> isTransparent;
00141         <span class="keywordtype">float</span> objRadius;
00142         <a class="code" href="group__aeObjRenderingModes.php#a0">aeObjRenderingMode</a> objRenderMode;
00143 
00144  <span class="keyword">public</span>:
00145         <span class="keyword">virtual</span> ~<a class="code" href="classaeObject.php">aeObject</a>();
00146 
00153         <span class="keyword">virtual</span> <span class="keywordtype">char</span> *<a class="code" href="classaeObject.php#a1">GetName</a>();
00154 
00161         <span class="keyword">virtual</span> <a class="code" href="classaeMaterial.php">aeMaterial</a> *<a class="code" href="classaeObject.php#a2">GetMaterial</a>();
00162 
00168         <span class="keyword">virtual</span> <span class="keywordtype">void</span> <a class="code" href="classaeObject.php#a3">Draw</a>(<a class="code" href="structaeEngineflags.php">aeEngineflags</a> *) = 0;
00169 
00176         <span class="keyword">virtual</span> <a class="code" href="classaeVector3.php">aeVector3</a> <a class="code" href="classaeObject.php#a4">GetOrigin</a>();
00177 
00183         <span class="keyword">virtual</span> <span class="keywordtype">void</span> <a class="code" href="classaeObject.php#a5">SetOrigin</a>(<span class="keyword">const</span> <a class="code" href="classaeVector3.php">aeVector3</a> &amp;norigin);
00184 
00193         <span class="keyword">virtual</span> <span class="keywordtype">void</span> <a class="code" href="classaeObject.php#a6">SetColor</a>(<span class="keywordtype">float</span> r, <span class="keywordtype">float</span> g, <span class="keywordtype">float</span> b);
00194 
00204         <span class="keyword">virtual</span> <span class="keywordtype">void</span> <a class="code" href="classaeObject.php#a6">SetColor</a>(<span class="keywordtype">float</span> r, <span class="keywordtype">float</span> g, <span class="keywordtype">float</span> b, <span class="keywordtype">float</span> a);
00205 
00213         <span class="keyword">virtual</span> <span class="keywordtype">void</span> <a class="code" href="classaeObject.php#a6">SetColor</a>(<span class="keyword">const</span> <a class="code" href="classaeColor3.php">aeColor3</a> &amp;color);
00214 
00222         <span class="keyword">virtual</span> <span class="keywordtype">void</span> <a class="code" href="classaeObject.php#a6">SetColor</a>(<span class="keyword">const</span> <a class="code" href="classaeColor4.php">aeColor4</a> &amp;color);
00223 
00232         <span class="keyword">virtual</span> <span class="keywordtype">void</span> <a class="code" href="classaeObject.php#a10">SetTexCoord</a>(<span class="keyword">const</span> <a class="code" href="classaeTexCoord2.php">aeTexCoord2</a> &amp;texcoord);
00233 
00243         <span class="keyword">virtual</span> <span class="keywordtype">void</span> <a class="code" href="classaeObject.php#a10">SetTexCoord</a>(<span class="keywordtype">float</span> s, <span class="keywordtype">float</span> t);
00244 
00250         <span class="keyword">virtual</span> <span class="keywordtype">void</span> <a class="code" href="classaeObject.php#a12">SetMaterial</a>(<a class="code" href="classaeMaterial.php">aeMaterial</a> *mat);
00251 
00258         <span class="keyword">virtual</span> <span class="keywordtype">void</span> <a class="code" href="classaeObject.php#a13">AddVertex</a>(<span class="keyword">const</span> <a class="code" href="classaeVector3.php">aeVector3</a> &amp;vertex);
00259 
00265         <span class="keyword">virtual</span> <span class="keywordtype">void</span> <a class="code" href="classaeObject.php#a14">SetTransparent</a>(<span class="keywordtype">bool</span>);
00266 
00273         <span class="keyword">virtual</span> <span class="keywordtype">unsigned</span> <span class="keywordtype">int</span> <a class="code" href="classaeObject.php#a15">GetVertexCount</a>();
00274 
00282         <span class="keyword">virtual</span> <a class="code" href="classaeVector3.php">aeVector3</a> <a class="code" href="classaeObject.php#a16">GetVertex</a>(<span class="keywordtype">int</span>);
00283 
00290         <span class="keyword">virtual</span> <span class="keywordtype">float</span> <a class="code" href="classaeObject.php#a17">GetBoundingSphereRadius</a>();
00291 
00298         <span class="keyword">virtual</span> <span class="keywordtype">bool</span> <a class="code" href="classaeObject.php#a18">IsTransparent</a>();
00299 
00321         <span class="keyword">virtual</span> <span class="keywordtype">void</span> <a class="code" href="classaeObject.php#a19">SetMode</a>(aeObjRenderingMode mode);
00322 };
00323 
00324 <span class="preprocessor">#endif // __AELIB_AEGEOM_OBJECT_H__</span>
</pre></div><hr><address style="align: right;"><small>Generated on Sun Mar 2 01:14:22 2003 for AE Engine by
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border=0 
width=110 height=53></a>1.3-rc2 </small></address>
</body>
</html>
