<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>bmpHeader struct Reference</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.3-rc2 -->
<center>
<a class="qindex" href="index.php">Main Page</a> &nbsp; <a class="qindex" href="modules.php">Modules</a> &nbsp; <a class="qindex" href="hierarchy.php">Class Hierarchy</a> &nbsp; <a class="qindex" href="classes.php">Alphabetical List</a> &nbsp; <a class="qindex" href="annotated.php">Compound List</a> &nbsp; <a class="qindex" href="files.php">File List</a> &nbsp; <a class="qindex" href="functions.php">Compound Members</a> &nbsp; </center>
<hr><h1>bmpHeader Struct Reference<br>
<small>
[<a class="el" href="group__txtldrstructs.php">AE texture loader image structures</a>]</small>
</h1>BITMAPINFOHEADER struct. 
<a href="#_details">More...</a>
<p>
<code>#include &lt;<a class="el" href="txtldr_8h-source.php">txtldr.h</a>&gt;</code>
<p>
<a href="structbmpHeader-members.php">List of all members.</a><table border=0 cellpadding=0 cellspacing=0>
<tr><td></td></tr>
<tr><td colspan=2><br><h2>Public Attributes</h2></td></tr>
<tr><td nowrap align=right valign=top><a name="m0" doxytag="bmpHeader::biSize"></a>
<a class="el" href="group__aetypedefs.php#a4">uint32</a>&nbsp;</td><td valign=bottom><b>biSize</b></td></tr>
<tr><td nowrap align=right valign=top><a name="m1" doxytag="bmpHeader::biWidth"></a>
<a class="el" href="group__aetypedefs.php#a4">uint32</a>&nbsp;</td><td valign=bottom><b>biWidth</b></td></tr>
<tr><td nowrap align=right valign=top><a name="m2" doxytag="bmpHeader::biHeight"></a>
<a class="el" href="group__aetypedefs.php#a4">uint32</a>&nbsp;</td><td valign=bottom><b>biHeight</b></td></tr>
<tr><td nowrap align=right valign=top><a name="m3" doxytag="bmpHeader::biPlanes"></a>
<a class="el" href="group__aetypedefs.php#a2">uint16</a>&nbsp;</td><td valign=bottom><b>biPlanes</b></td></tr>
<tr><td nowrap align=right valign=top><a name="m4" doxytag="bmpHeader::biBitCount"></a>
<a class="el" href="group__aetypedefs.php#a2">uint16</a>&nbsp;</td><td valign=bottom><b>biBitCount</b></td></tr>
<tr><td nowrap align=right valign=top><a name="m5" doxytag="bmpHeader::biCompression"></a>
<a class="el" href="group__aetypedefs.php#a4">uint32</a>&nbsp;</td><td valign=bottom><b>biCompression</b></td></tr>
<tr><td nowrap align=right valign=top><a name="m6" doxytag="bmpHeader::biSizeImage"></a>
<a class="el" href="group__aetypedefs.php#a4">uint32</a>&nbsp;</td><td valign=bottom><b>biSizeImage</b></td></tr>
<tr><td nowrap align=right valign=top><a name="m7" doxytag="bmpHeader::biXPelsPerMeter"></a>
<a class="el" href="group__aetypedefs.php#a4">uint32</a>&nbsp;</td><td valign=bottom><b>biXPelsPerMeter</b></td></tr>
<tr><td nowrap align=right valign=top><a name="m8" doxytag="bmpHeader::biYPelsPerMeter"></a>
<a class="el" href="group__aetypedefs.php#a4">uint32</a>&nbsp;</td><td valign=bottom><b>biYPelsPerMeter</b></td></tr>
<tr><td nowrap align=right valign=top><a name="m9" doxytag="bmpHeader::biClrUsed"></a>
<a class="el" href="group__aetypedefs.php#a4">uint32</a>&nbsp;</td><td valign=bottom><b>biClrUsed</b></td></tr>
<tr><td nowrap align=right valign=top><a name="m10" doxytag="bmpHeader::biClrImportant"></a>
<a class="el" href="group__aetypedefs.php#a4">uint32</a>&nbsp;</td><td valign=bottom><b>biClrImportant</b></td></tr>
</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
BITMAPINFOHEADER struct.
<p>

<p>
Definition at line <a class="el" href="txtldr_8h-source.php#l00075">75</a> of file <a class="el" href="txtldr_8h-source.php">txtldr.h</a>.<hr>The documentation for this struct was generated from the following file:<ul>
<li><a class="el" href="txtldr_8h-source.php">txtldr.h</a></ul>
<hr><address style="align: right;"><small>Generated on Sun Mar 2 01:14:23 2003 for AE Engine by
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border=0 
width=110 height=53></a>1.3-rc2 </small></address>
</body>
</html>
