<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>framePoint_t struct Reference</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.3-rc2 -->
<center>
<a class="qindex" href="index.php">Main Page</a> &nbsp; <a class="qindex" href="modules.php">Modules</a> &nbsp; <a class="qindex" href="hierarchy.php">Class Hierarchy</a> &nbsp; <a class="qindex" href="classes.php">Alphabetical List</a> &nbsp; <a class="qindex" href="annotated.php">Compound List</a> &nbsp; <a class="qindex" href="files.php">File List</a> &nbsp; <a class="qindex" href="functions.php">Compound Members</a> &nbsp; </center>
<hr><h1>framePoint_t Struct Reference<br>
<small>
[<a class="el" href="group__mdlldrstructs.php">AE model loader structures</a>]</small>
</h1>A single frame point structure. 
<a href="#_details">More...</a>
<p>
<code>#include &lt;<a class="el" href="mdlstruct_8h-source.php">mdlstruct.h</a>&gt;</code>
<p>
<a href="structframePoint__t-members.php">List of all members.</a><table border=0 cellpadding=0 cellspacing=0>
<tr><td></td></tr>
<tr><td colspan=2><br><h2>Public Attributes</h2></td></tr>
<tr><td nowrap align=right valign=top><a name="m0" doxytag="framePoint_t::v"></a>
unsigned char&nbsp;</td><td valign=bottom><a class="el" href="structframePoint__t.php#m0">v</a> [3]</td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>The point info.</em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top><a name="m1" doxytag="framePoint_t::normalIndex"></a>
unsigned char&nbsp;</td><td valign=bottom><a class="el" href="structframePoint__t.php#m1">normalIndex</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Normal index.</em></font><br><br></td></tr>
</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
A single frame point structure.
<p>

<p>
Definition at line <a class="el" href="mdlstruct_8h-source.php#l00049">49</a> of file <a class="el" href="mdlstruct_8h-source.php">mdlstruct.h</a>.<hr>The documentation for this struct was generated from the following file:<ul>
<li><a class="el" href="mdlstruct_8h-source.php">mdlstruct.h</a></ul>
<hr><address style="align: right;"><small>Generated on Sun Mar 2 01:14:23 2003 for AE Engine by
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border=0 
width=110 height=53></a>1.3-rc2 </small></address>
</body>
</html>
