<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>aeEngineflags struct Reference</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.3-rc2 -->
<center>
<a class="qindex" href="index.php">Main Page</a> &nbsp; <a class="qindex" href="modules.php">Modules</a> &nbsp; <a class="qindex" href="hierarchy.php">Class Hierarchy</a> &nbsp; <a class="qindex" href="classes.php">Alphabetical List</a> &nbsp; <a class="qindex" href="annotated.php">Compound List</a> &nbsp; <a class="qindex" href="files.php">File List</a> &nbsp; <a class="qindex" href="functions.php">Compound Members</a> &nbsp; </center>
<hr><h1>aeEngineflags Struct Reference</h1>Engine flags structure. 
<a href="#_details">More...</a>
<p>
<code>#include &lt;<a class="el" href="eflags_8h-source.php">eflags.h</a>&gt;</code>
<p>
<a href="structaeEngineflags-members.php">List of all members.</a><table border=0 cellpadding=0 cellspacing=0>
<tr><td></td></tr>
<tr><td colspan=2><br><h2>Public Attributes</h2></td></tr>
<tr><td nowrap align=right valign=top><a name="m0" doxytag="aeEngineflags::hasMultitexture"></a>
bool&nbsp;</td><td valign=bottom><a class="el" href="structaeEngineflags.php#m0">hasMultitexture</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>True if multitexturing is supported.</em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top>bool&nbsp;</td><td valign=bottom><a class="el" href="structaeEngineflags.php#m1">doMultipass</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Use multipass rendering or not.</em> <a href="#m1"></a><em></em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top><a name="m2" doxytag="aeEngineflags::texUnits"></a>
int&nbsp;</td><td valign=bottom><a class="el" href="structaeEngineflags.php#m2">texUnits</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Number of texture units.</em></font><br><br></td></tr>
</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
Engine flags structure.
<p>

<p>
Definition at line <a class="el" href="eflags_8h-source.php#l00030">30</a> of file <a class="el" href="eflags_8h-source.php">eflags.h</a>.<hr><h2>Member Data Documentation</h2>
<a name="m1" doxytag="aeEngineflags::doMultipass"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"> bool aeEngineflags::doMultipass
      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Use multipass rendering or not.
<p>
If multitexturing is not supported, this flag indicates whether to use multipass multitexturing (true) or completely disable multitexturing (false). It's set to true by default.
<p>
Definition at line <a class="el" href="eflags_8h-source.php#l00039">39</a> of file <a class="el" href="eflags_8h-source.php">eflags.h</a>.    </td>
  </tr>
</table>
<hr>The documentation for this struct was generated from the following file:<ul>
<li><a class="el" href="eflags_8h-source.php">eflags.h</a></ul>
<hr><address style="align: right;"><small>Generated on Sun Mar 2 01:14:23 2003 for AE Engine by
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border=0 
width=110 height=53></a>1.3-rc2 </small></address>
</body>
</html>
