<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>aeEvent struct Reference</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.3-rc2 -->
<center>
<a class="qindex" href="index.php">Main Page</a> &nbsp; <a class="qindex" href="modules.php">Modules</a> &nbsp; <a class="qindex" href="hierarchy.php">Class Hierarchy</a> &nbsp; <a class="qindex" href="classes.php">Alphabetical List</a> &nbsp; <a class="qindex" href="annotated.php">Compound List</a> &nbsp; <a class="qindex" href="files.php">File List</a> &nbsp; <a class="qindex" href="functions.php">Compound Members</a> &nbsp; </center>
<hr><h1>aeEvent Struct Reference<br>
<small>
[<a class="el" href="group__eventstructs.php">AE event structs and definitions.</a>]</small>
</h1>The AE event structure. 
<a href="#_details">More...</a>
<p>
<code>#include &lt;<a class="el" href="event_8h-source.php">event.h</a>&gt;</code>
<p>
<a href="structaeEvent-members.php">List of all members.</a><table border=0 cellpadding=0 cellspacing=0>
<tr><td></td></tr>
<tr><td colspan=2><br><h2>Public Attributes</h2></td></tr>
<tr><td nowrap align=right valign=top><a name="m0" doxytag="aeEvent::type"></a>
<a class="el" href="group__eventstructs.php#a3">aeEventType</a>&nbsp;</td><td valign=bottom><a class="el" href="structaeEvent.php#m0">type</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Event type.</em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top><a name="m1" doxytag="aeEvent::cmd"></a>
<a class="el" href="structaeEventCommand.php">aeEventCommand</a>&nbsp;</td><td valign=bottom><a class="el" href="structaeEvent.php#m1">cmd</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Event command.</em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top><a name="m2" doxytag="aeEvent::active"></a>
<a class="el" href="structaeActiveEvent.php">aeActiveEvent</a>&nbsp;</td><td valign=bottom><a class="el" href="structaeEvent.php#m2">active</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Active event.</em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top><a name="m3" doxytag="aeEvent::key"></a>
<a class="el" href="structaeKeyboardEvent.php">aeKeyboardEvent</a>&nbsp;</td><td valign=bottom><a class="el" href="structaeEvent.php#m3">key</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Keyboard event.</em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top><a name="m4" doxytag="aeEvent::motion"></a>
<a class="el" href="structaeMouseMotionEvent.php">aeMouseMotionEvent</a>&nbsp;</td><td valign=bottom><a class="el" href="structaeEvent.php#m4">motion</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Mouse motion event.</em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top><a name="m5" doxytag="aeEvent::button"></a>
<a class="el" href="structaeMouseButtonEvent.php">aeMouseButtonEvent</a>&nbsp;</td><td valign=bottom><a class="el" href="structaeEvent.php#m5">button</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Mouse button event.</em></font><br><br></td></tr>
<tr><td nowrap align=right valign=top><a name="m6" doxytag="aeEvent::quit"></a>
<a class="el" href="structaeQuitEvent.php">aeQuitEvent</a>&nbsp;</td><td valign=bottom><a class="el" href="structaeEvent.php#m6">quit</a></td></tr>
<tr><td>&nbsp;</td><td><font size=-1><em>Quit event.</em></font><br><br></td></tr>
</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
The AE event structure.
<p>

<p>
Definition at line <a class="el" href="event_8h-source.php#l00426">426</a> of file <a class="el" href="event_8h-source.php">event.h</a>.<hr>The documentation for this struct was generated from the following file:<ul>
<li><a class="el" href="event_8h-source.php">event.h</a></ul>
<hr><address style="align: right;"><small>Generated on Sun Mar 2 01:14:23 2003 for AE Engine by
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border=0 
width=110 height=53></a>1.3-rc2 </small></address>
</body>
</html>
