<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>Member List</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.3-rc2 -->
<center>
<a class="qindex" href="index.php">Main Page</a> &nbsp; <a class="qindex" href="modules.php">Modules</a> &nbsp; <a class="qindex" href="hierarchy.php">Class Hierarchy</a> &nbsp; <a class="qindex" href="classes.php">Alphabetical List</a> &nbsp; <a class="qindex" href="annotated.php">Compound List</a> &nbsp; <a class="qindex" href="files.php">File List</a> &nbsp; <a class="qindex" href="functions.php">Compound Members</a> &nbsp; </center>
<hr><h1>bmpHeader Member List</h1>This is the complete list of members for <a class="el" href="structbmpHeader.php">bmpHeader</a>, including all inherited members.<table>
  <tr bgcolor="#f0f0f0"><td><b>biBitCount</b> (defined in <a class="el" href="structbmpHeader.php">bmpHeader</a>)</td><td><a class="el" href="structbmpHeader.php">bmpHeader</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td><b>biClrImportant</b> (defined in <a class="el" href="structbmpHeader.php">bmpHeader</a>)</td><td><a class="el" href="structbmpHeader.php">bmpHeader</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td><b>biClrUsed</b> (defined in <a class="el" href="structbmpHeader.php">bmpHeader</a>)</td><td><a class="el" href="structbmpHeader.php">bmpHeader</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td><b>biCompression</b> (defined in <a class="el" href="structbmpHeader.php">bmpHeader</a>)</td><td><a class="el" href="structbmpHeader.php">bmpHeader</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td><b>biHeight</b> (defined in <a class="el" href="structbmpHeader.php">bmpHeader</a>)</td><td><a class="el" href="structbmpHeader.php">bmpHeader</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td><b>biPlanes</b> (defined in <a class="el" href="structbmpHeader.php">bmpHeader</a>)</td><td><a class="el" href="structbmpHeader.php">bmpHeader</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td><b>biSize</b> (defined in <a class="el" href="structbmpHeader.php">bmpHeader</a>)</td><td><a class="el" href="structbmpHeader.php">bmpHeader</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td><b>biSizeImage</b> (defined in <a class="el" href="structbmpHeader.php">bmpHeader</a>)</td><td><a class="el" href="structbmpHeader.php">bmpHeader</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td><b>biWidth</b> (defined in <a class="el" href="structbmpHeader.php">bmpHeader</a>)</td><td><a class="el" href="structbmpHeader.php">bmpHeader</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td><b>biXPelsPerMeter</b> (defined in <a class="el" href="structbmpHeader.php">bmpHeader</a>)</td><td><a class="el" href="structbmpHeader.php">bmpHeader</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td><b>biYPelsPerMeter</b> (defined in <a class="el" href="structbmpHeader.php">bmpHeader</a>)</td><td><a class="el" href="structbmpHeader.php">bmpHeader</a></td><td></td></tr>
</table><hr><address style="align: right;"><small>Generated on Sun Mar 2 01:14:23 2003 for AE Engine by
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border=0 
width=110 height=53></a>1.3-rc2 </small></address>
</body>
</html>
