<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>pcxHeader struct Reference</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.3-rc2 -->
<center>
<a class="qindex" href="index.php">Main Page</a> &nbsp; <a class="qindex" href="modules.php">Modules</a> &nbsp; <a class="qindex" href="hierarchy.php">Class Hierarchy</a> &nbsp; <a class="qindex" href="classes.php">Alphabetical List</a> &nbsp; <a class="qindex" href="annotated.php">Compound List</a> &nbsp; <a class="qindex" href="files.php">File List</a> &nbsp; <a class="qindex" href="functions.php">Compound Members</a> &nbsp; </center>
<hr><h1>pcxHeader Struct Reference<br>
<small>
[<a class="el" href="group__txtldrstructs.php">AE texture loader image structures</a>]</small>
</h1>(A partial) PCX file header. 
<a href="#_details">More...</a>
<p>
<code>#include &lt;<a class="el" href="txtldr_8h-source.php">txtldr.h</a>&gt;</code>
<p>
<a href="structpcxHeader-members.php">List of all members.</a><table border=0 cellpadding=0 cellspacing=0>
<tr><td></td></tr>
<tr><td colspan=2><br><h2>Public Attributes</h2></td></tr>
<tr><td nowrap align=right valign=top><a name="m0" doxytag="pcxHeader::manufacturer"></a>
unsigned char&nbsp;</td><td valign=bottom><b>manufacturer</b></td></tr>
<tr><td nowrap align=right valign=top><a name="m1" doxytag="pcxHeader::version"></a>
unsigned char&nbsp;</td><td valign=bottom><b>version</b></td></tr>
<tr><td nowrap align=right valign=top><a name="m2" doxytag="pcxHeader::encoding"></a>
unsigned char&nbsp;</td><td valign=bottom><b>encoding</b></td></tr>
<tr><td nowrap align=right valign=top><a name="m3" doxytag="pcxHeader::bits"></a>
unsigned char&nbsp;</td><td valign=bottom><b>bits</b></td></tr>
<tr><td nowrap align=right valign=top><a name="m4" doxytag="pcxHeader::xMin"></a>
unsigned char&nbsp;</td><td valign=bottom><b>xMin</b></td></tr>
<tr><td nowrap align=right valign=top><a name="m5" doxytag="pcxHeader::yMin"></a>
unsigned char&nbsp;</td><td valign=bottom><b>yMin</b></td></tr>
<tr><td nowrap align=right valign=top><a name="m6" doxytag="pcxHeader::xMax"></a>
unsigned char&nbsp;</td><td valign=bottom><b>xMax</b></td></tr>
<tr><td nowrap align=right valign=top><a name="m7" doxytag="pcxHeader::yMax"></a>
unsigned char&nbsp;</td><td valign=bottom><b>yMax</b></td></tr>
<tr><td nowrap align=right valign=top><a name="m8" doxytag="pcxHeader::palette"></a>
unsigned char *&nbsp;</td><td valign=bottom><b>palette</b></td></tr>
</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
(A partial) PCX file header.
<p>

<p>
Definition at line <a class="el" href="txtldr_8h-source.php#l00092">92</a> of file <a class="el" href="txtldr_8h-source.php">txtldr.h</a>.<hr>The documentation for this struct was generated from the following file:<ul>
<li><a class="el" href="txtldr_8h-source.php">txtldr.h</a></ul>
<hr><address style="align: right;"><small>Generated on Sun Mar 2 01:14:23 2003 for AE Engine by
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border=0 
width=110 height=53></a>1.3-rc2 </small></address>
</body>
</html>
